### ISSUE TITLE
GCP create-infrastructure fails

### ISSUE THREAD

**Issue by mhausmann-pivotal** [pivotal-cf/pcf-pipelines#100]
The create-infastructure task fails just after generating the certs with the following errors:

`Error loading state: Failed to check for magic bytes: EOF`
`error running command: no matches found for pattern: create-infrastructure-output/*.tfstate`

**Comment by krishicks** [comment]
This has been updated. Please remove the empty file that was placed in your S3 bucket under `bucket/terraform.tfstate` and try again with the latest code.
