### ISSUE TITLE
upgrade-ert fails for while downloading stemcells

### ISSUE THREAD

**Issue by nebhale** [pivotal-cf/pcf-pipelines#102]
Last night while trying to upgrade to Elastic Runtime 1.10.11, my pipelines (0.14.1, 1c90ccc7c4883a3d8ec2ccab23dcf23e120bc6e6) failed in the `wait-opsman-clear
` task with the following error:

```
Could not login to ops man
could not execute "curl": failed to make api request: failed submitting request: token could not be retrieved from target url: Post https://https/uaa/oauth/token: dial tcp: lookup https on 10.192.2.10:53: no such host
```

It would appear that the task has changed incompatibly with existing pipelines and since the pipelines always look to the latest commit, most previously released versions of `pcf-pipelines` are now unusable.

**Comment by krishicks** [comment]
This is due to a change in how the opsman URI is specified in the params, as per https://github.com/pivotal-cf/pcf-pipelines/commit/48ffc5ab2351aadf361a92b0d4a569e785b384f4

If you remove the protocol from the URI it should work. Re-open this issue if it does not.

**Comment by krishicks** [comment]
Also, the Github release is not pegged to any specific version, unlike the Pivnet release. That means it will move ahead while your pipeline falls behind.

This is a known issue but that we have no pressing concern to address as the Github release isn't the official release; the Pivnet one is.
