### ISSUE TITLE
upload-products-and-stemcells task.sh script failing

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pcf-pipelines#104]
Script immediately exists if stemcell is not found:

    root@2441defd-7956-46e9-51f5-f8d74bfd9b84:/tmp/build/8ac8d33d# pcf-pipelines/tasks/upload-
    product-and-stemcell/task.sh
    + [[ ! -z '' ]]
    ++ cat ./pivnet-product/metadata.json
    ++ jq --raw-output '.Dependencies[] | select(.Release.Product.Name | contains("Stemcells")) | .Release.Version'
    + STEMCELL_VERSION=3363.20
    + '[' -n 3363.20 ']'
    ++ om-linux -t https://URL -u admin -p PW -k curl --silent --path /api/v0/diagnostic_report
    ++ jq .stemcells
    ++ grep 3363.20
    ++ grep -c vsphere
    + stemcell_exists=0

if I modify the code inside the if statement to the following it works as expected but is not as elegant as it could be:

    if [ -n "$STEMCELL_VERSION" ]; then
      #stemcell_exists=$(om-linux -t https://$OPS_MGR_HOST -u $OPS_MGR_USR -p $OPS_MGR_PWD -k curl --silent --path "/api/v0/diagnostic_report" | jq '.stemcells' | grep $STEMCELL_VERSION | grep -c ${STEMCELL_GLOB//\*/})

      if [[ $(om-linux -t https://$OPS_MGR_HOST -u $OPS_MGR_USR -p $OPS_MGR_PWD -k curl --silent --path "/api/v0/diagnostic_report" | jq '.stemcells' | grep $STEMCELL_VERSION | grep -c ${STEMCELL_GLOB//\*/}) = 0 ]]; then
      #if [$stemcell_exists -eq "0" ]; then
        echo "Downloading stemcell $STEMCELL_VERSION"
        pivnet-cli login --api-token="$PIVNET_API_TOKEN"
        pivnet-cli download-product-files -p stemcells -r $STEMCELL_VERSION -g $STEMCELL_GLOB --accept-eula

    root@2441defd-7956-46e9-51f5-f8d74bfd9b84:/tmp/build/8ac8d33d# pcf-pipelines/tasks/upload-product-and-stemcell/task.sh
    + [[ ! -z '' ]]
    ++ cat ./pivnet-product/metadata.json
    ++ jq --raw-output '.Dependencies[] | select(.Release.Product.Name | contains("Stemcells")) | .Release.Version'
    + STEMCELL_VERSION=3363.20
    + '[' -n 3363.20 ']'
    ++ om-linux -t https://URL-u admin -p PW -k curl --silent --path /api/v0/diagnostic_report
    ++ jq .stemcells
    ++ grep 3363.20
    ++ grep -c vsphere
    + [[ 0 = 0 ]]
    + echo 'Downloading stemcell 3363.20'
    Downloading stemcell 3363.20
    + pivnet-cli login --api-token=TOKEN
    Logged-in successfully
    + pivnet-cli download-product-files -p stemcells -r 3363.20 -g bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz --accept-eula
    2017/06/02 06:58:05 Downloading 'bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz' to 'bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz'
     41.89 MB / 406.59 MB [====>---------------------------------------]  10.30% 17s

**Comment by bhudlemeyer** [comment]
Believe I have tracked this down to bash exit code handling. The command returns a code of 0 this appears to cause the shell script to exit immediately as bash -e is set.

Removing the -e allows the script to run as expected. 

    root@2441defd-7956-46e9-51f5-f8d74bfd9b84:/tmp/build/8ac8d33d# pcf-pipelines/tasks/upload-product-and-stemcell/task.sh
    + [[ ! -z '' ]]
    ++ cat ./pivnet-product/metadata.json
    ++ jq --raw-output '.Dependencies[] | select(.Release.Product.Name | contains("Stemcells")) | .Release.Version'
    + STEMCELL_VERSION=3363.20
    + '[' -n 3363.20 ']'
    ++ om-linux -t https://URL -u admin -p PW -k curl --silent --path /api/v0/diagnostic_report
    ++ jq .stemcells
    ++ grep 3363.20
    ++ grep -c vsphere
    + stemcell_exists=0
    + [[ 0 -eq 0 ]]
    + echo 'Downloading stemcell 3363.20'
    Downloading stemcell 3363.20
    + pivnet-cli login --api-token=TOKEN
    Logged-in successfully
    + pivnet-cli download-product-files -p stemcells -r 3363.20 -g bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz --accept-eula
    2017/06/02 07:57:39 Downloading 'bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz' to 'bosh-stemcell-3363.20-vsphere-esxi-ubuntu-trusty-go_agent.tgz'
     42.48 MB / 406.59 MB [====>---------------------------------------]  10.45% 16s

**Comment by krishicks** [comment]
Thanks for the bug report.

Fixed in https://github.com/pivotal-cf/pcf-pipelines/commit/648ba7e24f936e126a77f90cc4d822a874bbdc64.
