### ISSUE TITLE
wait-opsman-clear task polls indefinitely if a historical task is remains marked as running 

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/pcf-pipelines#107]
Apologize for the horrible summary to this issue so I will attempt to illustrate what happened.  We had a scenario a few days ago where a tile update was pushed to our system that resulted in a hang in applying the changes through the ops manager (12 + hours).  We were unable to cancel the task and so we had to restart the ops manager and bosh director VMs in order for the lock to clear and the task to be marked as failed on the bosh side.  We worked with pivotal support to fix the bosh deployment manually by leveraging bosh and resolved the issue that was causing the hang.  We were able to apply changes through the OpsManager UI however, applying changes using pcf-piplines would hang on the task wait-opsman-clear.  

I did some digging this morning and found that the change_log view in the ops manager had a install that was still marked as running but it was not the most recent install.  I looked into the task.sh for wait-for-opsman-clear and found the API call /api/v0/installations would return the list of recent installations.  I dug around and found that this information was stored in the postgres database on the OpsMan VM and updated the row from status running to status failed similar to the following ```/usr/lib/postgresql/9.3/bin/psql -d tempest_production -c "update installs set status = 'falied' where id = 169"```  I was able to find the row using the CLI with the following ```/usr/lib/postgresql/9.3/bin/psql -d tempest_production -c "select id, status from installs where status = 'running'"``` I should stress that this was the 4 or 5 installs ago and not the most recent one because we were able to apply changes still using the OpsMan UI.  

One simple fix would be to query on the most recent installation status https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/wait-opsman-clear/task.sh#L45 instead of all installation status.  In doing so we would be able to know that the first installation status is equal to running and if so wait. 

The other issue I found was my pcf-pipelines would all wait at this point with not apparent timeout, so a timeout would also be a useful addition.

**Comment by geoffwa** [comment]
👍 happened to me too, although I just deleted the stale running install 😄

**Comment by abbyachau** [comment]
Thanks @xyloman and @geoffwa for your feedback; apologies for the late response. We are closing this issue in favour of this pr, which addresses your concerns above: https://github.com/pivotal-cf/pcf-pipelines/pull/177. Please follow that pr and attached story for further developments. Thanks.
