### ISSUE TITLE
ERT 1.11.0 currently introduces breaking change to config-ert task

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pcf-pipelines#109]
ERT 1.11 has removed the property

    ".diego_cell.garden_network_pool"

This causes ERT config to fail with 

    {"errors":{".diego_cell.garden_network_pool":["is not a property"]}

The file that needs to be modified once ERT 1.11 is Ga is 

    pcf-pipelines/tasks/config-ert/load_cf_properties.sh

**Comment by abbyachau** [comment]
Hi @bhudlemeyer, we are closing this issue because we've implemented a fix. Please let us know if you have any feedback or run into any problems pertaining to this issue, thanks.
