### ISSUE TITLE
Deploy to aws,error for configure-director

### ISSUE THREAD

**Issue by emperorente** [pivotal-cf/pcf-pipelines#116]
I got the error like "could not execute "configure-bosh": could not fetch form: could not find the form authenticity token", what does it mean?

**Comment by ryanpei** [comment]
@emperorente sounds like your params are incomplete?

**Comment by emperorente** [comment]
I have no idea which params was missed, Here are my params which I didn't fill in:
director_certificates:
ERT_SSL_KEY:
PEM: (private key for login into aws? )

**Comment by emperorente** [comment]
solve it, put the wrong PEM.close the issue

**Comment by emperorente** [comment]
unfortunately, it fails when I deploy it again, first time was succeed cause I fill some parameters manually on the first page, after that, I trigger the "configure-director", I still have no idea which params i missed!!

**Comment by emperorente** [comment]
opsmgr version:1.10.9
seems like opsman's problem, when I execute the om with the params separately like:

1.om --target https://x.x.x.x --skip-ssl-validation --username test --password 'test' configure-bosh --iaas-configuration '{ data 
}'  , It response "configuring iaas specific options for bosh tile
finished configuring bosh tile" ,sounds like success, but opsman didn't save the params,

2.om --target https://x.x.x.x --skip-ssl-validation --username test --password 'test' configure-bosh 
--iaas-configuration --director-configuration  --az-configuration, it response 
"configuring iaas specific options for bosh tile
configuring director options for bosh tile
configuring availability zones for bosh tile
could not execute "configure-bosh": could not fetch form: could not find the form authenticity token"

3.when I  use the "configure-director" pipelines shows params fill in the opsman manually, everything is ok.

so maybe the new version of opsmgr change itself's api response or the om's problem??

**Comment by abbyachau** [comment]
hey @emperorente, could you please post the error message you received when you triggered `configure-director`? 

You've probably seen this already but there is a list of [params](https://github.com/pivotal-cf/pcf-pipelines/tree/master/install-pcf/aws) that should be filled out prior to triggering the pipeline. 

We've also published a few new [releases](https://github.com/pivotal-cf/pcf-pipelines/releases) recently, so it might help if you upgrade to the latest version if you can.

**Comment by jpluscplusm** [comment]
I kept seeing this error, and I tracked it down to the following:

If `om configure-bosh --iaas-configuration` doesn't contain all the necessary parameters (I was missing the correctly encoded private key contents due to `bash`isms ...), then *none* of the contents of the "AWS Config" tab gets saved. This includes the access keys, without which the "Create Availability Zones" tab can't be filled in programatically via `--az-configuration`.

The fundamental problem IMHO is with om (version == 0.23.0) or OpsMan itself, in that an *incorrect* or incomplete `--iaas-configuration` isn't obvious.

To demonstrate this, try an otherwise-correct `om -iaas-configuration` invocation leaving the private key field blank. I see exit status 0 and the same output as a successful invocation. That, to me, is the real bug here.

**Comment by emperorente** [comment]
@abbyachau  Here is the error message when I trigger the "configure-director", 

'configuring iaas specific options for bosh tile
configuring director options for bosh tile
configuring availability zones for bosh tile
could not execute "configure-bosh": could not fetch form: could not find the form authenticity token'

**Comment by emperorente** [comment]
@jpluscplusm @abbyachau  any plans for this issue?

**Comment by krishicks** [comment]
"could not find the form authenticity token" means it failed to make a request to Operations Manager. I'd check that your opsman domain is set correctly (omit the protocol).

Also, a lot has changed since this issue was opened. We're now on 1.11; please run the pipeline again and re-open this issue if it's still a concern.

**Comment by emperorente** [comment]
HI, i use the latest 1.11 version , but it shows the same error
![image](https://user-images.githubusercontent.com/15973223/28632540-7dbd7392-7263-11e7-9142-9c46a2bd7ba9.png)

**Comment by emperorente** [comment]
update error info when use om cli:


could not execute "configure-bosh": tile failed to configure: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Wed, 26 Jul 2017 16:41:06 GMT
Server: nginx/1.4.6 (Ubuntu)
Set-Cookie: _web_session=aEFQQjB5Uk1NcWNBRUNkcUFYY0VBZm9oaE92MDUwR2pYY1Z3Ty9YSXJlZXNsa3BLbzVueEpkZHNnZ0loSndZUHh4N0IwVjZzcGY2cVFJVjhXS1E4SVNEZFh1MEIrZzdxL2JIVmp2aU84QlYrbzRITWl1SkRkMHJsamIvam1jR0JVbUEyNUN2bHphSlVBenJTOTRUQndBPT0tLUxWdjFtRy9wL292Q3FrL2dJbWkxSVE9PQ%3D%3D--e819a45687995463eacb158444e7839125ebbeb0; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 7a7a1a49-279a-42de-92fe-65e338b67082
X-Runtime: 0.452129
X-Xss-Protection: 1; mode=block

**Comment by abbyachau** [comment]
Hi @emperorente, v0.15.4 is the latest version of pcf-pipelines, please try again with this version and let us know if you run into the same issues. Please also make sure that for the parameter for `opsman_uri`, you do not include the protocol.  And also ensure that you have all the necessary credentials filled out correctly (`TF_VAR_aws_access_key`, `TF_VAR_aws_secret_key`, `PEM`, etc - see the explanation of each parameter in the `params.yml` file for AWS). Thanks.

**Comment by emperorente** [comment]
solved!,3ks
