### ISSUE TITLE
Integrate yaml-patch into the czero/cflinuxfs2 Docker image

### ISSUE THREAD

**Issue by lsilvapvt** [pivotal-cf/pcf-pipelines#117]
As customers start using the yaml-patch tool to customize their deployments of the pcf-pipelines, it would be great to have it readily available as part of the czero/cflinuxfs2, so they can more easily create their customization pipelines without the need to download the tool on an ad-hoc basis in custom tasks.

**Comment by krishicks** [comment]
Seems reasonable. If we do this we should also include testpipe.

**Comment by abbyachau** [comment]
Thanks, @lsilvapvt. Closing this issue because we've implemented a fix - please let us know if you have any feedback. Thanks again.
