### ISSUE TITLE
pivnet-opsmgr can't fetch the version when deploy concourse by docker

### ISSUE THREAD

**Issue by emperorente** [pivotal-cf/pcf-pipelines#118]
I have deployed a concourse to ec2 by docker, but when I start the pipeline, can't fetch the pivnet-opsmgr version, here is the pic
![test](https://user-images.githubusercontent.com/15973223/27074082-94dff9c8-5058-11e7-8d4b-8a51b77bf303.jpeg)

**Comment by krishicks** [comment]
Try running `fly -t yourtarget check-resource -r yourpipeline/pivnet-opsmgr` to see if it's able to check the resource successfully.

**Comment by emperorente** [comment]
checked 'pivnet-opsmgr' means ok?

**Comment by krishicks** [comment]
That means Concourse is able to see new versions of the resource but something else is limiting it, perhaps a `passed` constraint on an upstream job.

Which pipeline are you running, and what version of pcf-pipelines?

**Comment by emperorente** [comment]
it works now, maybe some networks problem, thanks, I'll close it
