### ISSUE TITLE
Username and Password parameters for Autoscale DB user are backwards in install-pcf/gcp/params.yml

### ISSUE THREAD

**Issue by cbguder** [pivotal-cf/pcf-pipelines#119]
The `db_autoscale_username` and `db_autoscale_password` parameters in `install-pcf/gcp/params.yml` are backwards, causing some confusion when quickly pasting auto-generated passwords into this file.

**Comment by abbyachau** [comment]
Hey @cbguder, we've completed this change. We'll close out this issue but feel free to reopen it if you have any problems. Thanks.
