### ISSUE TITLE
Tile upgrades break after stemcell-downloader was removed from czero/cflinuxfs2 dockerfile

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/pcf-pipelines#120]
After this change set was pushed:

https://github.com/pivotal-cf/pcf-pipelines/commit/59c0e796d2cbf3a102f1c9ac2390f0a4966db3ef

I started to notice AWS and OpenStack pcf-pipeline failures around stemcell-downloader command missing 
```
pcf-pipelines/tasks/upload-stemcell/task.sh: line 26: stemcell-downloader: command not found
```
Currently using pcf-piplines 0.15.0 from pivnet.

**Comment by krishicks** [comment]
Ah, good catch.

Due to backwards-compatibility we can't remove things from the rootfs, so I've restored both stemcell-downloader and om-linux-beta.

**Comment by krishicks** [comment]
The new image is now available, digest is sha256:b99d8e3da5b023da0da44c5cb550dc005adaa8fe118fc69ccb449a0db8a60a93

**Comment by xyloman** [comment]
This appears to solve the issue that I was having.  Thanks.

**Comment by abbyachau** [comment]
Great, thank you @xyloman.
