### ISSUE TITLE
Implement support for OpenStack iaasType for upgrade-ops-manager pipeline

### ISSUE THREAD

**Issue by xyloman** [pivotal-cf/pcf-pipelines#124]
Currently we leverage all of the other pipeline capabilities on our OpenStack setup of PCF however, upgrade-ops-manager pipeline currently does not have support for PCF.

**Comment by abbyachau** [comment]
Hi @xyloman, many thanks for creating this issue. Since the OpenStack upgrade ops manager pipeline is no longer on our roadmap, we plan on closing this issue. Please let us know if you have any questions or feedback. Thanks.
