### ISSUE TITLE
deploy-opsman-vm for vSphere does not allow the disk type to be configured

### ISSUE THREAD

**Issue by dwntwnbrown** [pivotal-cf/pcf-pipelines#126]
Currently in the deploy-opsman-vm/task.sh the following is hard coded "DiskProvisioning":"thin". This should be a configurable parameter.

**Comment by abbyachau** [comment]
Hi @dwntwnbrown thanks for raising this issue, and sorry about the delay. There is a related pr for this issue here: https://github.com/pivotal-cf/pcf-pipelines/pull/147. We are closing this issue in favour of the pr - please follow developments there. Thanks!
