### ISSUE TITLE
Inconsistencies with variable names 

### ISSUE THREAD

**Issue by benfab** [pivotal-cf/pcf-pipelines#128]
Hello,

I have noticed some inconsistencies between the name of variables used for the params in the upgrade-tile pipeline. For instance, the same variable is called "OPSMAN_USERNAME" and then called "OPS_MGR_USR" few lines below. See the lines:
https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-tile/pipeline.yml#L73
https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-tile/pipeline.yml#L82

Fixing these inconsistencies would help to maintain the pipelines.
Thanks!

**Comment by krishicks** [comment]
This is a known issue that we'll be addressing as we consolidate params.
