### ISSUE TITLE
can't access the opsman url use the latest releases

### ISSUE THREAD

**Issue by emperorente** [pivotal-cf/pcf-pipelines#130]
Hi, I update to the latest code, and deploy it to aws, however, I can't access the opsman url, I notice that there're some new params in the pcf-pipelines/install-pcf/aws/params.yml,  does it matter?

**Comment by ryanpei** [comment]
@emperorente can you please add this info here to help us get familiar with your issue:
- which versions of the pipelines and of PCF you were using
- the error message you found
