### ISSUE TITLE
Import settings timeout to small on the om tool

### ISSUE THREAD

**Issue by pakiheart** [pivotal-cf/pcf-pipelines#137]
Ran into the following error:
![pasted image at 2017_06_28 02_51 pm](https://user-images.githubusercontent.com/12705327/27689502-0423e734-5ca4-11e7-8992-c950062f1d18.png)

Upgrade Ops Manager pipeline failed during import settings.  These exports/imports can take a very long time as more and more tiles are added.   30 min default time out is not long enough.  We need to bump that or set it in params file.
Rollback is also painful, only option is to delete the new OM and restart the old OM and re run the entire pipeline, these take long time due to the size.

**Comment by krishicks** [comment]
This is something we can easily change and should change; the timeout needs to take into account the fact that importing settings of 50GB or more as has been described by others due to many installed tiles.

I suggest we extend the timeout to 24 hours, or another reasonable and very high timeout.

**Comment by abbyachau** [comment]
Hi @pakiheart, thanks for reporting this issue. Closing this issue because we've applied a fix. If you run into any further issues or have any feedback, please let us know by creating a new issue. Thanks.
