### ISSUE TITLE
Mismatch between documentation and actual parameters - install on AWS

### ISSUE THREAD

**Issue by findneville** [pivotal-cf/pcf-pipelines#140]
Documentation link: https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/aws/README.md
Params file: https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/aws/params.yml

Fix 1
AWS RDS username and password section defined as below does not exist in the params file
    ```
      TF_VAR_rds_db_username: bosh
      TF_VAR_rds_db_password: boshbosh
    ```  

`db_master_username` and `db_master_password` exist but the terraform plan fails with these values fail since they are inputs for Terraform

Should be `TF_VAR_db_master_username` and `TF_VAR_db_master_password` instead

Fix 2 

AWS prefix for provisioned resources. This is used to differentiate different deploy environment by prefixing the AWS resources (E.g. ELB and S3 buckets)
    ```
      TF_VAR_environment: sandbox
    ```
There is no `TF_VAR_environment` variable in the params file. There is a `terraform_prefix` which also does not work. Should be `TF_VAR_prefix`

Fix 3

Ops Manager AWS AMI defined as below does not exist in the params file

    ```
    TF_VAR_opsman_ami: ami-52c5e145
    ```

TF_VAR_opsman_ami has to be added to params file.

**Comment by findneville** [comment]
Once I have tested the actual installation, I will probably fork and do a pull request with the changes.

**Comment by krishicks** [comment]
This has been updated; the README mostly moved to the params.yml.
