### ISSUE TITLE
set 8 in readme - refactored out?

### ISSUE THREAD

**Issue by wjk940** [pivotal-cf/pcf-pipelines#145]
Is step 8 "Run the create-initial-terraform-state job manually" replaced, perhaps by bootstrap-terraform-state?

**Comment by wjk940** [comment]
not sure comment was for the specific file - https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/gcp/README.md

**Comment by krishicks** [comment]
Yeah, the job was renamed.

**Comment by abbyachau** [comment]
Hi @wjk940, we've updated the aforementioned README - thanks for creating this issue!
