### ISSUE TITLE
create-infrastructure - deleting ssl cert

### ISSUE THREAD

**Issue by wjk940** [pivotal-cf/pcf-pipelines#146]
* google_sql_user.locket: 1 error(s) occurred:

* google_sql_user.locket: Error, failed to insert user  into instance [INSTANCE]: googleapi: Error 400: Missing parameter: Missing user name., required
* google_compute_ssl_certificate.ssl-cert (destroy): 1 error(s) occurred:

* google_compute_ssl_certificate.ssl-cert: Error deleting ssl certificate: googleapi: Error 400: The ssl_certificate resource 'projects/[PROJECT]/global/sslCertificates/[PREFIX]-lb-cert' is already being used by 'projects/[PROJECT]/global/targetHttpsProxies/[PREFIX]-https-proxy', resourceInUseByAnotherResource

**Comment by wjk940** [comment]
there was no CHANGEME for db_silk and db_locket - I tried leaving them blank, but the are required - params.yml should have CHANGEME

cannot get past the google_compute_ssl_certificate.ssl-cert (destroy) error

**Comment by abbyachau** [comment]
See https://github.com/pivotal-cf/pcf-pipelines/issues/106

**Comment by ryanpei** [comment]
Closing this as a duplicate issue to #106
