### ISSUE TITLE
Including protocol in upgrade-ops-manager/aws/params.yml's opsman_uri causes errors

### ISSUE THREAD

**Issue by bbertka-pivotal** [pivotal-cf/pcf-pipelines#153]
When using the protocol in 'opsman_uri' we receive Concourse error message on "wait-opsman-clear":  

could not execute "curl": failed to make api request: failed submitting request: token could not be retrieved from target url:  Post https://https/uaa/oauth/token: dial tcp: lookup https on 10.0.0.2:53: no such host

in params.yml example includes http protocol:

# Ops Manager Url
# eg. https://myopsman.mydomain.com

Should be:

# Ops Manager Url
# eg. myopsman.mydomain.com

**Comment by geoffwa** [comment]
:+1: is also an issue with the vSphere pipeline, although the error is more cryptic for me:
```
Checking if you are applying an allowed patch upgrade @ https://opsman.localnet
parse error: Invalid numeric literal at line 1, column 6
You are trying to install version: 
1.11.5#2017-07-23T23:45:35.944Z
Your currently deployed version is: 
.

Pivotal recommends that you only automate
    patch upgrades of PCF, and perform major or minor
    upgrades manually to ensure that no high-impact
    changes to the platform are introduced without
    your prior knowledge.

To upgrade patch releases, we suggest using the following version regex in your params file:
^\\.\..*$
```

**Comment by abbyachau** [comment]
Hi @geoffwa, thanks for creating this issue. We already have a story in our backlog (https://www.pivotaltracker.com/story/show/148112387)  to prioritise renaming`opsman_uri` and to clarify that a protocol should not be included in the param. The second possibly related issue - please let us know if removing the protocol doesn't fix it and you continue to receive that error.

**Comment by abbyachau** [comment]
Closing this issue because we've accepted https://www.pivotaltracker.com/story/show/148112387, which clarifies the param name to indicate to operators not to include the protocol. If you have any feedback, please do not hesitate to reach out. Thanks.
