### ISSUE TITLE
install pipeline with S3 set as backup for mysql failing

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pcf-pipelines#154]
Deploy ERT task failing with below message when setting S3 as backup location

    configuring product...
    setting properties
    could not execute "configure-product": failed to configure product: request failed: unexpected response:
    HTTP/1.1 500 Internal Server Error
    Transfer-Encoding: chunked
    Cache-Control: no-cache
    Connection: keep-alive
    Content-Type: application/json; charset=utf-8
    Date: Tue, 25 Jul 2017 20:06:41 GMT
    Server: nginx/1.4.6 (Ubuntu)
    Strict-Transport-Security: max-age=31536000
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-Request-Id: 569f3618-b48b-45f6-b007-d33340ee3dc1
    X-Runtime: 0.716115
     X-Xss-Protection: 1; mode=block
    
    67
    {"errors":{"base":["undefined method `each' for \"PW\":String"]}}
    0

Opsman 1.11.5
ERT 1.11.5

**Comment by bhudlemeyer** [comment]
Setting to disable results in below response

`configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Wed, 26 Jul 2017 18:27:59 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 7cb48989-73e3-4505-843d-aa56dbcca9d2
X-Runtime: 0.823532
X-Xss-Protection: 1; mode=block

6f
{"errors":{".properties.route_services":["You can only change properties that are under the selected option"]}}
0
`

**Comment by bhudlemeyer** [comment]
I think I figured out what is going on here. I had route services set to disable in my param file. However route.services isnt inside an if/else statement in the config script. I added it as a if/else and am testing it now will report back if it resolves issue.

**Comment by bhudlemeyer** [comment]
I was incorrect this did resolve the properties.route.service error but the original error with mysql back remains. Disabling mysql backup allows install to continue.

**Comment by abbyachau** [comment]
Hey @bhudlemeyer, thanks for creating this issue. Please let us know what you've put for this parameter `mysql_backups_s3_cron_schedule`. Thanks.

**Comment by bhudlemeyer** [comment]
0 0 * * *

**Comment by bhudlemeyer** [comment]
0 0 * * *

**Comment by abbyachau** [comment]
Hi @bhudlemeyer, I'm just checking in to see if you've been able to use the `mysql_backups: enable` with the latest release of [pcf-pipelines](https://github.com/pivotal-cf/pcf-pipelines/releases)? Thanks.

**Comment by abbyachau** [comment]
Hey @bhudlemeyer checking in again to see if you are still seeing this issue. We've not been able to reproduce this issue. Please let us know, thanks.
