### ISSUE TITLE
PCF install scripts with config broken out from stage causing duplicate downloads

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pcf-pipelines#156]
Running through the vsphere install pipeline ERT gets downloaded twice currently. 

Braking out staging from config ert appears to have introduced a requirement that the .pivotal file be available in the staging task to get version information. This results in ERT getting downloaded in the Upload-ert task and deploy-ert task. 

![image](https://user-images.githubusercontent.com/2275490/28636801-2e785dac-71f4-11e7-9dd1-bc6addc43997.png)

![image](https://user-images.githubusercontent.com/2275490/28636699-d1ce406c-71f3-11e7-902e-54f58da39d50.png)

**Comment by abbyachau** [comment]
Hi @bhudlemeyer, thanks for raising this issue. We'll look into seeing if there is anything we can do to eliminate downloading the ERT tile twice.

**Comment by abbyachau** [comment]
Hi @bhudlemeyer apologies for the delay on this one. We do not have current plans to prioritise this work. We have captured it as something to look into at a future date. Thanks again for creating this issue.
