### ISSUE TITLE
Is vSphere Upgrade Ops Manager Ready?

### ISSUE THREAD

**Issue by nebhale** [pivotal-cf/pcf-pipelines#16]
Currently, looking at the parameters available in `vsphere/upgrade-ops-manager-params.yml`, the list seems much smaller than what the OpsManager UI exposes.  I'd expect it to be much larger (to recreate the original configuration) or much smaller (configuration imported from previously exported installation).

Is the Upgrade Ops Manager pipeline ready for use on vSphere installations?

**Comment by ryanpei** [comment]
@nebhale the upgrade pipeline works under the assumption that your Ops Manager is already configured, and its purpose is to just update the Ops Manager with the same configuration. There should very rarely be any new configurations required for patch upgrades. Minor/major upgrades can be a different story, but we only recommend using these pipelines for patch upgrades unless you can add a job yourself to do additional configuration if it's required.

**Comment by nebhale** [comment]
I agree that it should be able to just update with the existing information.  That leads to my question as to why it requires all the information about clusters, resource pools, vm folders, etc.  That information was already configured and should be reused.

**Comment by ryanpei** [comment]
This info is required to be able to spin up a new Ops Mgr VM in your vSphere infrastructure, since Ops Mgr is the only VM in PCF that you need to standup on any IaaS without bosh.
