### ISSUE TITLE
Pivotal Cloud Cache having inconsistent Product version and name in metadata.yml file

### ISSUE THREAD

**Issue by PlatOps** [pivotal-cf/pcf-pipelines#166]
Noticed the following issue with the PCC 1.1.0 tile which is breaking the automation via Concourse. Please let me know if we could get the product_version and product name to be consistent? Looks like some extra variables in there in each of the metadata head.

$ unzip -p p-cloudcache-1.0.6-build.1.pivotal "metadata/*.yml" | head
---
name: &product-name p-cloudcache
label: Pivotal CloudCache
service_broker: true
product_version: &product-version "1.0.6-build.1"
metadata_version: "1.8"
rank: 1
minimum_version_for_upgrade: "1.0.0"

$ $ unzip -p p-cloudcache-1.1.0-build.23.pivotal "metadata/*.yml" | grep 'product_version:' | cut -d ':' -f 2 | tr -d ' ' | tr -d "'"
&product-version"1.1.0-build.23"

**Comment by PlatOps** [comment]
Output from the v1.1.0 tile for Cloudcache

$ unzip -p p-cloudcache-1.1.0-build.23.pivotal "metadata/*.yml" | head
---
name: &product-name p-cloudcache
label: Pivotal CloudCache
service_broker: true
product_version: &product-version "1.1.0-build.23"
metadata_version: "1.10"
rank: 1

**Comment by krishicks** [comment]
This isn't an issue for us to resolve. I would talk to the tile authors.
