### ISSUE TITLE
Openstack install pipeline key creation

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/pcf-pipelines#168]
Can we create a key or use an existing public key (need to add a variable) in the OpenStack install pipeline.  https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/keypair.html

**Comment by ryanpei** [comment]
@skibum55 which would you prefer, the ability to add your own key or to auto-gen the key? or do you need both options?

**Comment by skibum55** [comment]
I'd prefer to use an existing key.

**Comment by abbyachau** [comment]
Hi @skibum55 closing this issue out because, from what I understand,  it does not relate to a specific customer use case. Please do not hesitate to get in touch if you have any feedback. Thanks.
