### ISSUE TITLE
error info when prepare-rds in aws

### ISSUE THREAD

**Issue by emperorente** [pivotal-cf/pcf-pipelines#169]
there's error info when I deploy PCF in aws , the error info bellows:
Warning: Permanently added 'ip address' (ECDSA) to the list of known hosts.
Enter passphrase for key 'pcf.pem': 

pcf-pipelines version :latest
pcf :1.10

**Comment by emperorente** [comment]
Resolve it！there's some blank space in pem file, I add 
![image](https://user-images.githubusercontent.com/15973223/29442176-861cb074-8402-11e7-94f1-ad10af141d42.png)in aws/tasks/prepare-rds/task.sh. but there's another error, did you do a test in aws when doing changes?

**Comment by emperorente** [comment]
wipe also got an error....:
pcf-pipelines/install-pcf/aws/tasks/wipe-env/task.sh: line 23: -var: command not found
![image](https://user-images.githubusercontent.com/15973223/29462572-67351ed4-8462-11e7-94e0-90eb5591f354.png)

**Comment by abbyachau** [comment]
@emperorente our pipelines support 1.11.1 and are not backwards compatible. In addition, we've done some additional work for the `wipe-env` job so you might want to reset your pipeline and try again. I can't tell whether any resources were created when you ran the pipeline above, but you may need to manually delete any resources first before resetting the pipeline. Thanks.
