### ISSUE TITLE
AWS region should be configurable for install-PCF pipeline

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/pcf-pipelines#174]
I want to use a region other than us-east-1

**Comment by abbyachau** [comment]
hey @ryanpei do you have more information on this one please? thanks.

**Comment by ryanpei** [comment]
When I filed this issue, someone in the field noted that they could not specify which region they wanted their VPC deployed. It always ends up in US East.

**Comment by fredwangwang** [comment]
As of today, this is configurable. If you find that this is incorrect, please reopen the issue.
