### ISSUE TITLE
AWS install pipeline should use 4443 for loggregator port

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/pcf-pipelines#175]
port 443 is the default value for loggregator port, and it needs to set as 4443

**Comment by emperorente** [comment]
May be that's why I can use cf logs command!!!

**Comment by emperorente** [comment]
I found the docs in pivotal as below:
![image](https://user-images.githubusercontent.com/15973223/29765222-e91e61a6-8c0c-11e7-808b-b11c393657c8.png)

**Comment by abbyachau** [comment]
Closing this issue because we've verified the fix. (In v0.16.0-rc.12) Thanks.
