### ISSUE TITLE
Upgrade Tile will fail for Staging the Product

### ISSUE THREAD

**Issue by dkothari-clgx** [pivotal-cf/pcf-pipelines#176]
I noticed that some of the tiles have a little extra stuff in their product_version and name:

example: 
 * product_version: &product-version "1.1.1-build.5"

This will fail for two reason: 
```sh
version="$(unzip -p *.pivotal 'metadata/*.yml' | grep 'product_version:' | cut -d ':' -f 2 | tr -d ' ' | tr -d "'")" d
```
* om-tool does not need &product-version.  
* om-tool does not want "" when staging. 

I have temporary solved it by adding
```
  version="${version/\&product-version}"
  version="${version%\"}"
  version="${version#\"}"
```
I am looking for a better solution though.

**Comment by abbyachau** [comment]
Hi @dkothari-clgx, thanks for raising this issue. Could you please let us know the tile you've implemented this workaround for? Or let us know of other tiles in which you recall seeing these extra characters. Thanks.

**Comment by Gifflen** [comment]
@abbyachau We've run into similar issues with the apigee tile. The metadata in the tile is 2.1.0 but the metadata on pivnet is 2.1 which is causing an expected `could not execute "stage-product": failed to stage product: cannot find product apigee-cf-service-broker 2.1` error

**Comment by dkothari-clgx** [comment]
@abbyachau so far I have only seen it only in P-Cloud-Cache Tile. I will try out @Gifflen method.

**Comment by abbyachau** [comment]
@dkothari-clgx thanks - we've just so happened to test with that product (p-cloud-cache) - still currently doing more work to fix this issue. thanks again.

@Gifflen thanks for that feedback. hopefully the fix will cover your use case as well, if not I'll write a story and put it in our backlog.

**Comment by nebhale** [comment]
I appear to be experiencing the same issue with the `upgrade-ert` pipeline (which I'm guessing utilizes the same code to stage the ERT tile).

![screen shot 2017-09-01 at 11 08 51](https://user-images.githubusercontent.com/60754/29982286-f7d923f6-8f05-11e7-8317-0c546a6f99f3.png)

**Comment by abbyachau** [comment]
thanks @nebhale, this is a known issue and we hope to fix it soon.

**Comment by nebhale** [comment]
@abbyachau This seems to still be broken, but in a different way:
![screen shot 2017-09-27 at 16 58 33](https://user-images.githubusercontent.com/60754/30923951-31445f44-a3a5-11e7-9bb0-98358cbec4c0.png)

**Comment by abbyachau** [comment]
Hi @nebhale, sorry for the delay. From your error message, it looks like a different issue unrelated to the one the OP opened. It looks like your task failed because there is an un-used product which has not been cleaned up prior to running the job again.  We have a story to fix this issue: https://www.pivotaltracker.com/story/show/151289561. The current workaround to go into the Ops Manager Installation board and clicking on the delete unused product button. If you are still running into a problem, please open a new issue. Thanks!
