### ISSUE TITLE
Wipe-env in GCP-install cannot delete UAA db

### ISSUE THREAD

**Issue by ryanpei** [pivotal-cf/pcf-pipelines#183]
Paul Hopper (PA) was trying to cleanup his GCP env and was hitting errors when the `wipe-env` job could not delete the `uaa` database in the Google Cloud SQL instance. He re-ran the job, and it still could not delete it. So he had to do the cleanup manually.

**Comment by ryanpei** [comment]
he was running PCF pipelines v. 0.16.0

**Comment by ryanpei** [comment]
this may just have been flakiness on GCP at the time

**Comment by abbyachau** [comment]
Closing this out because we haven't seen this error.
