### ISSUE TITLE
aws pipeline was waiting forever for versioned terraform.tfstate

### ISSUE THREAD

**Issue by cxhercules** [pivotal-cf/pcf-pipelines#188]
I kicked off aws pipeline and found that it just waited indefinitely. The way I finally got it to kickoff was to submit blank terraform.tfstate file to bucket.

**Comment by cxhercules** [comment]
So I see there is a bootstrap terraform job, so supposed this is not needed, maybe just called out in documentation.

**Comment by abbyachau** [comment]
Thanks @cxhercules, we've prioritised this issue.

**Comment by abbyachau** [comment]
Thanks @cxhercules we've updated the documentation to include what you've suggested: https://github.com/pivotal-cf/pcf-pipelines/tree/master/install-pcf/aws#error.
