### ISSUE TITLE
om_network_name param does not allow spaces in the value

### ISSUE THREAD

**Issue by wrast** [pivotal-cf/pcf-pipelines#19]
The network name in the `params.yml` file for property `om_vm_network` does not support space characters in the value (e.g. `VLAN 26`). The resulting network name is just `VLAN`.

The root cause appears to be this line in `tasks/import-opsman/task.sh`:

```
  setNetworkMapping $OM_VM_NETWORK
```

The `$OM_VM_NETWORK` variable should be quoted.

**Comment by wrast** [comment]
We have tested and verified that there are 2 changes that fix this specific issue:

1) Add double-quotes around the `$OM_VM_NETWORK` variable:

```
setNetworkMapping "$OM_VM_NETWORK"
```

2) Add double-quotes around the `$1` variable in the `setNetworkMapping` function:

```
function setNetworkMapping() {
  if [ -e out.json ]; then
    mv out.json in.json
  fi
  jq --arg value "$1" \
     '(.NetworkMapping[]).Network = $value' \
                in.json >out.json
}
```

This is currently the only area where we are concerned with fixing the spaces issue, however there are undoubtedly other areas in the code where spaces should be handled better. So adding quotes around variables should be looked at more closely.

**Comment by ryanpei** [comment]
this should now work, @wrast . thanks for the feedback!
