### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by cforce** [pivotal-cf/pcf-pipelines#190]
The pcf network link to pipelines distro is broken

**Comment by cashell** [comment]
To add additional info, all of the links/URLs that reference PCF Automation such as:
> Please use the [Pivotal Network release](https://network.pivotal.io/products/pcf-automation/) of pcf-pipelines for stability. Using this repo directly may result in breaking the piplines that consume it. Tracking master is considered unstable.

Are broken.

The URL https://network.pivotal.io/products/pcf-automation/ doesn't seem to be valid.

**Comment by abbyachau** [comment]
Hi @cforce and @cashell, I believe this was a temporary issue and is now resolved. If you are still running into this issue, let us know. Thanks.

**Comment by elric392** [comment]
Appears to still be broken ..... 

![image](https://user-images.githubusercontent.com/31511398/31125918-12592642-a818-11e7-8535-7e004ddcc436.png)

**Comment by cforce** [comment]
No more Shame..but it's still. broken..🤩

**Comment by abbyachau** [comment]
@cforce @elric392 you may not have access to that page. Sorry about the delay on this - will verify and get back to you asap.

**Comment by abbyachau** [comment]
Hi @cforce and @elric392 it's likely you both do not have access to that page and unfortunately I cannot give you access to it because it is not accessible to the general public. You could use the github release, but please keep in mind this is not the most stable version of the pipelines.

**Comment by abbyachau** [comment]
Hi @cforce and @elric392 we are closing this issue but please let us know if you have any feedback/questions by opening a new issue. Thanks.
