### ISSUE TITLE
aws instance type not supported in availability zone.

### ISSUE THREAD

**Issue by cxhercules** [pivotal-cf/pcf-pipelines#193]
So seems m3.large is no longer supported in us-east-1a...

```
* aws_instance.opsmman_az1: 1 error(s) occurred:

* aws_instance.opsmman_az1: Error launching source instance: Unsupported: Your requested instance type (m3.large) is not supported in your requested Availability Zone (us-east-1a). Please retry your request by not specifying an Availability Zone or choosing us-east-1c, us-east-1b, us-east-1d, us-east-1e.
	status code: 400, request id: 5ce7f28f-66ae-4f07-97c6-5ab5c2644487
```

**Comment by abbyachau** [comment]
Hi @cxhercules sorry for the delay in response. What version of the pipelines are you using? Are you getting it from PivNet or Github? Thanks.

**Comment by cxhercules** [comment]
I am using GitHub for testing, and using following git hash:

```
commit 4a1dd60a63e47a0681f23118f3221f56191e7b8d 
Author: Slawek Ligus <sligus@pivotal.io>
Date:   Mon Sep 18 16:14:49 2017 -0700

    Highlight which binaries are missing

    [#150067976] pivotal-cf/cliaas #6: AWS replace-vm does not honour IAM Roles

    Signed-off-by: Christian Ang <cang@pivotal.io>
```

I will try with latest later this week, thanks!

**Comment by abbyachau** [comment]
Hi @cxhercules, wanted to check in to see whether this worked for you, and if so, could we close this issue. Thanks!

**Comment by krishicks** [comment]
Given the [opsman_instance_type](https://github.com/pivotal-cf/pcf-pipelines/blob/30d5b752ae17e274b170c9c94ce993b543f17b9c/install-pcf/aws/terraform/variables.tf#L31) var isn't configurable, I don't see why this would work any differently now than it did at 4a1dd60a63e47a0681f23118f3221f56191e7b8d.

There are two ways for these vars to be configurable:
* an environment variable prefixed with `TF_VAR_`, as it's done here: https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/aws/tasks/prepare-aws/task.yml#L14
* an arg passed to the call to `terraform`, as it's done here: https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/aws/tasks/prepare-aws/task.sh#L23

**Comment by abbyachau** [comment]
hey @krishicks thanks for this information. @cxhercules closing this issue. Please do not hesitate to get in touch again should you run into any issues.

**Comment by krishicks** [comment]
😕

**Comment by abbyachau** [comment]
new thread for this issue: https://github.com/pivotal-cf/pcf-pipelines/pull/194
