### ISSUE TITLE
[Doc] Misleading comment on regex string

### ISSUE THREAD

**Issue by wrast** [pivotal-cf/pcf-pipelines#195]
This commented line is a bit misleading by having the double-quotes surrounding the example. I think it is worth further comment to explicitly state to **not** use double-quotes. YAML would then escape the characters and provide an incorrect string to the pipeline. Line 22 provides a properly un-double-quoted string as it should. Single-quotes is also acceptable here.

https://github.com/pivotal-cf/pcf-pipelines/blob/0b09f5ef6f772933642a40aca30a6696b2c3a4f2/upgrade-tile/params.yml#L21

**Comment by abbyachau** [comment]
Hey thanks, @wrast included an add-on to that text but left the quotes as is.
