### ISSUE TITLE
apply-updates regulator job doesn't regulate anything

### ISSUE THREAD

**Issue by krishicks** [pivotal-cf/pcf-pipelines#201]
https://github.com/pivotal-cf/pcf-pipelines/blob/dbb274353035b0d54d04057af9904a8d8e94e9fe/apply-updates/pipeline.yml#L26

The apply-updates regulator job is currently being triggered on the schedule alone; in this configuration the job has no meaning.

See https://github.com/concourse/concourse/issues/945 for an explanation of the regulator concept.

**Comment by krishicks** [comment]
The changes made to this pipeline remove the regulator, but still get the implementation incorrect.

In the event that there is an updated stemcell available it will download that stemcell, and upload it. The `apply-changes` job will then run apply changes.

In the event that there is not an updated stemcell available, it will simply state "No new stemcells available, skipping upload." and exit successfully, meaning `apply-updates` will still run. This isn't free; OpsMgr will take time trying to apply changes even when there are none.

Also, the default configuration means this Apply Changes will run once per day, every day, whether there are updates or not.

**Comment by abbyachau** [comment]
Hi @krishicks thanks for that feedback. Two stories have been created to address your feedback: https://www.pivotaltracker.com/story/show/152622902 and https://www.pivotaltracker.com/story/show/152622921.

**Comment by abbyachau** [comment]
Hi @krishicks instead of leaving this issue open so that we could get to the issues you described, we've decided to close it and add a Known [Issues](https://github.com/pivotal-cf/pcf-pipelines/blob/master/apply-updates/README.md) section to the Apply Updates README. Thanks again for the feedback.
