### ISSUE TITLE
Incorporate encryption of stem cells into the upgrade pipeline

### ISSUE THREAD

**Issue by uknadkarni** [pivotal-cf/pcf-pipelines#202]
Please incorporate the encryption of stem cells into the PCF upgrade pipeline with Concourse.

**Comment by abbyachau** [comment]
Hi @uknadkarni, I believe someone has reached out to you for more information, and for some context regarding your ask. Please let us know whether you want to keep this issue open, or rather you are happy to go through a different channel. Thanks.

**Comment by abbyachau** [comment]
Hi @uknadkarni, please let us know whether you have more information, or whether you are going through a different channel for this issue. If the latter, we'll close this issue. Thanks.

**Comment by abbyachau** [comment]
Hi @uknadkarni, deleting this issue because I believe you've handled this query via a different channel. If that's incorrect, please do not hesitate to reopen or create a new issue. Thanks.
