### ISSUE TITLE
upgrade-ops-manager only checks for running/pending changes before exporting settings but not after

### ISSUE THREAD

**Issue by eamonryan** [pivotal-cf/pcf-pipelines#205]
The current initial task order for `upgrade-ops-manager` is:

```- name: upgrade-opsmgr
  - task: wait-opsman-clear
  - task: export-opsmgr-settings
  - task: exported-opsmgr-diagnostic-report
  - task: deploy-opsman-vm
```

However, the `export-opsmgr-settings` task can take upwards of 10 minutes to complete, given that it is generating a rather large file.

It is possible for some user (or pipeline) to add in a pending change or begin an apply-changes operation during this long time window.

Can we account for this by adding a new check after the settings have been exported that fails the pipeline if new changes are detected *or* runs a new `wait-opsman-clear` and then re-exports the settings before continuing?

**Comment by abbyachau** [comment]
Hi @eamonryan, we just published [v22](https://github.com/pivotal-cf/pcf-pipelines/releases/tag/v0.22.0) which contains this enhancement. Please do not hesitate to reach out if you have any feedback. Thanks again.
