### ISSUE TITLE
Ability to update default container network

### ISSUE THREAD

**Issue by pakiheart** [pivotal-cf/pcf-pipelines#208]
.properties.container_networking_network_cidr - ability to modify that

**Comment by abbyachau** [comment]
Hi @pakiheart, thanks for raising this issue. Could you talk about your use case please, for example, are you trying to use c2c networking, and attempting to avoid ip collision?

**Comment by pakiheart** [comment]
@abbyachau it is due to ip collision

**Comment by abbyachau** [comment]
Thanks, @pakiheart, prioritising.

**Comment by abbyachau** [comment]
Hi @pakiheart, thanks for raising this issue. We've implemented a new param `container_networking_nw_cidr` to allow you to configure the overlay subnet. Please do not hesitate to give us feedback by creating a new issue, thanks.
