### ISSUE TITLE
on GCP the configure-director resource step config-opsman-auth fails

### ISSUE THREAD

**Issue by phopper-pivotal** [pivotal-cf/pcf-pipelines#213]
on GCP the configure-director resource step config-opsman-auth fails with error

could not execute "configure-authentication": could not determine initial configuration status: could not make request round trip: Get https://opsman.hoppers.io/login/ensure_availability: dial tcp: i/o timeout

after adding the ip address and hostname to /etc/hosts file script runs to completion.

do note the curl command as part of check-opsman-dns task is successful in resolving against DNS and maps to correct IP.

from the concourse container;

```
# nslookup opsman.hoppers.io
Server:		169.254.169.254
Address:	169.254.169.254#53

Non-authoritative answer:
Name:	opsman.hoppers.io
Address: 104.154.167.243
```

Since I have to run this step manually I cannot proceed to the last task in the resource to `configure-director`

**Comment by oozie** [comment]
Hi @phopper-pivotal.

It's interesting indeed given that the address resolves. Let me see if I understand the mitigative action:
1) The concourse job failed.
2) The `opsman` entry got added to `/etc/hosts` on the hijacked docker container
3) Running the script manually from the docker container with spliced `/etc/hosts` has succeeded.

Is this correct? If, so I have a few questions:
* Was the job re-run from concourse? Did re-running of the same concourse job fail the same way?
* Is it possible that `opsman.hoppers.io` record was set in the DNS within 5 minutes before the job ran?
* Is the issue reproducible at present?

**Comment by phopper-pivotal** [comment]
@oozie that is correct. once I modified the /etc/hosts to map host to IP address it worked. However I cannot move on to the next step of the pipeline/job to fully configure the ops director and apply changes. so I'm stuck at the moment.

yes. running the same job repeatedly results in same error and is reproducible.

`could not execute "configure-authentication": could not determine initial configuration status: could not make request round trip: Get https://opsman.hoppers.io/login/ensure_availability: dial tcp: i/o timeout`

DNS was set 24-hours before running that job of the pipeline.

feel free to hit me up on slack as well.

**Comment by oozie** [comment]
The first nameserver on the docker container does not resolve at all `nameserver 10.0.0.6`

**Comment by phopper-pivotal** [comment]
@oozie you can close this ticket. 10.0.0.6 is the bosh director. it appears it no longer existed so rebuild concourse deployment from previous terraform state.

step passes.

**Comment by oozie** [comment]
Thanks @phopper-pivotal
