### ISSUE TITLE
Offline Upgrade Pipelines

### ISSUE THREAD

**Issue by FaKeller** [pivotal-cf/pcf-pipelines#219]
I've noticed that the upgrade pipelines are not ready for offline (airgapped) usage. For example, the upgrade pipelines make use of the `upload-product-and-stemcell` task which always looks up the corresponding stemcell version in the Pivotal network:

https://github.com/pivotal-cf/pcf-pipelines/blob/56320c38357aa50ec3b0fabb956ae319ee900f0e/tasks/upload-product-and-stemcell/task.sh#L58-L59

Are there any plans on bringing offline support for the upgrade pipelines? As the stemcell download is coded into the `task.sh` file, building a yaml-patch will not be sufficient I guess. 

One option I currently see would be to split the task into two tasks - one for downloading the stemcell (passing it as concourse `output`) and another one similar to the current one to upload both artifacts (requiring both as concourse `input`s). Would that be a viable solution for a contribution?

**Comment by sbayyapureddy** [comment]
Thank you. If you can update us on timelines once it is scheduled that will be helpful

**Comment by kstrini** [comment]
Hey Fabian! I believe the original intent for the offline pipelines is _to create_ the necessary artifact repos in order to use pcf pipelines offline. So this pipeline would be used with access to public internet in order to grab everything from pivnet. We then typically put them within an S3 structured repo. When then configure the pcf pipelines to point at this once we are in the offline environment. The naming is a bit of a misnomer I think.

**Comment by FaKeller** [comment]
Hey @kstrini, thanks for your answer! We are currently aiming to build an airgapped upgrade pipeline, which means we are planning to use the PCF pipelines as a base for that. However, the `create-offline-pinned-pipelines` currently only downloads and packs the artifacts and rewrites the `pcf-install` pipeline to make use of the offline artifacts, and not the upgrade pipelines:

https://github.com/pivotal-cf/pcf-pipelines/blob/78f01175fb458d3a9d5d6253875e9398d1fefb36/create-offline-pinned-pipelines/pipeline.yml#L393-L397

The problem we are facing is that the `upgrade-tile` pipeline uses the `upload-product-and-stemcell` task as mentioned above, which in turn tries to download the stemcell from pivnet:

https://github.com/pivotal-cf/pcf-pipelines/blob/78f01175fb458d3a9d5d6253875e9398d1fefb36/upgrade-tile/pipeline.yml#L76-L77

So currently we cannot implement airgapped upgrade pipelines out-of-the-box.

**Comment by abbyachau** [comment]
Hi @FaKeller, many thanks for your interest in the airgapped pipelines. Would you be able to speak more about your use case? We currently do not have a upgrade-tile pipeline for airgapped environments, but it would be great to understand how you are using the pipelines. Thanks.

**Comment by FaKeller** [comment]
Hi @abbyachau, we currently have multiple completely airgapped PCF foundations, which means that all management components (OpsManager, BOSH director, jumpbox servers, and administrators workstations) do not have internet access. Only some isolation segments that are intended to host public-facing apps are reachable from the internet. 

We are planning to automate the upgrades to these foundations with the help of the pcf-pipelines project. Our current idea is to use an S3-compatible server to provide the artifacts we need for the upgrades, namely the `.pivotal` files, stemcells, and all the required tools (pcf-pipelines, jq, ...). An update would then involve uploading a new artifact to the S3 server, from which concourse would automatically trigger the pipelines. In the long run, we also consider integrating buildpack updates and the replicator tool (for the various isolation segments) into the pipeline setup.

As I've been following the pcf-pipelines project for some time I think what we have as additional requirements for our offline setup is:

- Compared to the `install-pcf` pipelines we see the S3 storage as a place to continuously put new versions of all the artifacts, though populating the S3 storage might already be a bit out of scope for the pcf-pipelines project. As the `install-pcf` pipeline relies on a huge tar file with all artifacts we cannot reuse this part.
- Have the `upgrade-tile` pipeline only fetch resources from the S3 server, which is the reason why I opened this ticket. From what I've seen is that if we properly handle the tile->stemcell fetching from S3, the `upgrade-tile` pipeline should be offline ready.

**Comment by abbyachau** [comment]
Hi @FaKeller thanks for that information. We do not currently have a offline upgrade-tile pipeline but would definitely appreciate a contribution toward that effort. We have briefly looked into what a offline upgrade-tile pipeline would look like and determined that it could be possible to split the pipeline such that one pipeline pulls down new versions of the tile, inspects the stemcell it requires, and then uploads both to S3. Then, another pipeline would pull down the tile and stemcell from S3. Please let us know if you have any feedback.

**Comment by abbyachau** [comment]
Hi @FaKeller closing this issue as our roadmap does not immediately include work for the upgrade pipelines for offline environments. Please do not hesitate to create a new issue or get in touch should you have any questions, thanks.
