### ISSUE TITLE
Tile installed which requires CentOS breaks the OpsMan Upgrade pipeline

### ISSUE THREAD

**Issue by sneal** [pivotal-cf/pcf-pipelines#221]
For example, if you have the Apigee Edge tile installed the OpsMan Upgrade pipeline will not work because the [tile requires CentOS](https://docs.apigee.com/release-notes/content/41705-edge-installer-pivotal-cloud-foundry-release-notes). The output from the download-stemcells step will be similar to this:

```
Logged-in successfully
2017/11/07 23:15:44 Downloading 'bosh-stemcell-3312.38-vsphere-esxi-ubuntu-trusty-go_agent.tgz' to '/tmp/build/4064abe8/stemcells/bosh-stemcell-3312.38-vsphere-esxi-ubuntu-trusty-go_agent.tgz'
 407.17 MB / 407.17 MB [===========================================] 100.00% 52s
Could not find the required stemcell version 3312.7. This version might not be published on PivNet yet, try again later.
```

**Comment by abbyachau** [comment]
Thanks for logging this issue @sneal. Prioritizing for work.

**Comment by abbyachau** [comment]
Hi @sneal, the team's created a new ops file to support your use case. Please review the tracker story above for more information. The ops file can be found at [here](https://github.com/pivotal-cf/pcf-pipelines/blob/master/operations/add-download-boshio-stemcell.yml). Any questions, please do not hesitate to reach out. Thanks.
