### ISSUE TITLE
Deployment on GCP not possible with routing_disable_http = false

### ISSUE THREAD

**Issue by RomRider** [pivotal-cf/pcf-pipelines#224]
The deployment on GCP is not possible when setting the `routing_disable_http` parameter to `false` because the health checks on a GCP load balancer needs to be the same protocol as the backend. i.e. backend was deployed with https only, health checks should have been configured in https.
This is currently not possible on the gorouter.

Bug submitted by: @ckunst & @RomRider

**Comment by RomRider** [comment]
See #225 as a proposed short term workaround.

**Comment by abbyachau** [comment]
Hi @RomRider, thanks again for raising this issue. Closing this issue as we've reviewed your original request in #225 and decided not to pull it in in favour of the [pr](https://github.com/cloudfoundry/gorouter/issues/199) you've created with the routing team. Please do not hesitate to reach out should you have any questions/feedback. Thanks.
