### ISSUE TITLE
Uprade tile pipeline fails if there are multiple versions of same product available in the Ops Manager 

### ISSUE THREAD

**Issue by pratsury22** [pivotal-cf/pcf-pipelines#227]
The "stage-tile" task fails as it finds multiple versions of the same product. 
Below is the output from Concourse pipeline:
################################################
Need exactly one unstaged build for p-redis version 1.10.0
[
  {
    "name": "p-isolation-segment",
    "product_version": "1.11.6"
  },
  {
    "name": "p-windows-runtime",
    "product_version": "1.11.3"
  },
  {
    "name": "p-redis",
    "product_version": "1.10.0"
  },
  {
    "name": "p-rabbitmq",
    "product_version": "1.9.3"
  },
  {
    "name": "cf",
    "product_version": "1.11.14"
  }
]
##############################################################

Fixed the issue with a workaround by deleting the unused products from Ops Manager.  Need to add this code to the task.sh script for future usage.

[root@acldlp01pcf scripts]# ./om-linux --skip-ssl-validation --username admin --password <OPSMAN_PASSWORD> --target <OPSMAN_DOMAIN_OR_IP_ADDRESS> curl -path /api/v0/available_products
Status: 200 OK
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 14 Nov 2017 21:01:05 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 38e0bee7-8327-43af-988e-c6f48c279096
X-Runtime: 1.393724
X-Xss-Protection: 1; mode=block
[
  {
    "name": "p-isolation-segment",
    "product_version": "1.12.6"
  },
  {
    "name": "cf",
    "product_version": "1.12.5"
  },
  {
    "name": "bosh-hm-forwarder",
    "product_version": "0.0.24"
  },
  {
    "name": "splunk-nozzle",
    "product_version": "1.0.0"
  },
  {
    "name": "p-spring-cloud-services",
    "product_version": "1.4.3"
  },
  {
    "name": "p-windows-runtime",
    "product_version": "1.12.3"
  },
  {
    "name": "p-mysql",
    "product_version": "1.10.0"
  },
  {
    "name": "sumo-logic-nozzle",
    "product_version": "0.1.2"
  },
  {
    "name": "p-redis",
    "product_version": "1.9.3"
  },
  {
    "name": "p-metrics",
    "product_version": "1.9.2"
  },
  {
    "name": "p-isolation-segment",
    "product_version": "1.11.6"
  },
  {
    "name": "p-windows-runtime",
    "product_version": "1.11.3"
  },
  {
    "name": "p-windows-runtime-isoseg",
    "product_version": "1.12.3"
  },
  {
    "name": "p-rabbitmq",
    "product_version": "1.10.5"
  },
  {
    "name": "p-redis",
    "product_version": "1.10.0"
  },
  {
    "name": "p-rabbitmq",
    "product_version": "1.9.3"
  },
  {
    "name": "cf",
    "product_version": "1.11.14"
  }
]

[root@acldlp01pcf scripts]# ./om-linux --skip-ssl-validation --username admin -password <OPSMAN_PASSWORD> --target <OPSMAN_DOMAIN_OR_IP_ADDRESS> delete-unused-products
trashing unused products
done

[root@acldlp01pcf scripts]# ./om-linux --skip-ssl-validation --username admin -password <OPSMAN_PASSWORD> --target <OPSMAN_DOMAIN_OR_IP_ADDRESS> curl -path /api/v0/available_products
Status: 200 OK
Cache-Control: no-cache, no-store
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 14 Nov 2017 21:08:56 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Pragma: no-cache
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=15552000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 10469939-3af8-4208-996c-1cf824e2b353
X-Runtime: 0.992134
X-Xss-Protection: 1; mode=block
[
  {
    "name": "p-isolation-segment",
    "product_version": "1.12.6"
  },
  {
    "name": "cf",
    "product_version": "1.12.5"
  },
  {
    "name": "bosh-hm-forwarder",
    "product_version": "0.0.24"
  },
  {
    "name": "splunk-nozzle",
    "product_version": "1.0.0"
  },
  {
    "name": "p-spring-cloud-services",
    "product_version": "1.4.3"
  },
  {
    "name": "p-windows-runtime",
    "product_version": "1.12.3"
  },
  {
    "name": "p-mysql",
    "product_version": "1.10.0"
  },
  {
    "name": "sumo-logic-nozzle",
    "product_version": "0.1.2"
  },
  {
    "name": "p-redis",
    "product_version": "1.9.3"
  },
  {
    "name": "p-metrics",
    "product_version": "1.9.2"
  },
  {
    "name": "p-windows-runtime-isoseg",
    "product_version": "1.12.3"
  },
  {
    "name": "p-rabbitmq",
    "product_version": "1.10.5"
  }
]

I have added the code for this under my branch:

https://github.com/pratsury22/pcf-pipelines/pull/1

**Comment by abbyachau** [comment]
Hi @pratsury22 thanks for reporting this. This is a known issue which we've applied a fix for and we hope to release soon. Please look out for v21 when it comes out; that version of the pipelines will contain the fix for this issue. Thanks.

**Comment by abbyachau** [comment]
Hi @pratsury22 we've released [v21](https://github.com/pivotal-cf/pcf-pipelines/releases) which contains the fix to the issue you've seen above. Please switch to this version of the pipelines and let us know if you have any feedback by opening a new issue. Thanks.
