### ISSUE TITLE
Valid yaml syntax for trusted_certs does not translate well to json

### ISSUE THREAD

**Issue by wrast** [pivotal-cf/pcf-pipelines#23]
In `params.yml` file's `trusted_certs` property (and `ssl_cert` property), multi-line values are allowed by YAML. Example:

```
trusted_certs: |
  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----
```

This doesn't translate correctly into JSON during the `configure-ops-director/config-opsdir` task. JSON does not allow multiline values. Using a multiline yaml value for a certificate causes a `400 Bad Request` when configuring security.

The workaround is to make the certificate value a single line value in the yaml file. We used `\r\n` in place of hard return characters. However, it would be a nice fix to be able to specify a certificate as a multiline value as yaml syntax allows.

**Comment by bhudlemeyer** [comment]
I am sure you found this already but a quick work around for all certs and keys to turn them into single line format that works is:


`
awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' cert-name.pem --> Will output key/cert in single line format. 
`

**Comment by krishicks** [comment]
@wrast This is perhaps fixed now; we spent some effort to change how we handle certs to allow for multiline YAML strings.

**Comment by krishicks** [comment]
I've just checked and this isn't fixed yet. We need to use `jq` to handle this properly in these locations:

https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/config-ert/task.sh#L306

and

https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/config-opsdir/task.sh#L134

**Comment by krishicks** [comment]
I think this would work:

```
read -r -d '' security_filter <<'EOF'
  .security_configuration = {
    generate_vm_passwords: $generate_vm_passwords,
    trusted_certificates: $trusted_certificates
  }
EOF

SECURITY_CONFIG=$(
  echo '{}' |
  jq \
    --arg trusted_certificates "$TRUSTED_CERTIFICATES" \
    --argjson generate_vm_passwords $GENERATE_VM_PASSWORDS \
    "$security_filter"
)
```

**Comment by krishicks** [comment]
This is fixed in config-ert/task.sh.

**Comment by krishicks** [comment]
Fixed in config-opsdir/task.sh in https://github.com/pivotal-cf/pcf-pipelines/commit/621bf50

**Comment by abbyachau** [comment]
Hi @wrast, closing this issue because we've implemented a fix. If you have any feedback or run into any other issues, please let us know. Thanks.
