### ISSUE TITLE
Support for the small footprint ERT for install and upgrades

### ISSUE THREAD

**Issue by norman-abramovitz** [pivotal-cf/pcf-pipelines#232]
For companies who do not need a large PCF environment or doing tile development, it would be nice to be able to install and upgrade using pipelines.     For the tile developers whom might need tear down and rebuild their PCF environments, having a pipeline to do that would be very helpful. #

**Comment by abbyachau** [comment]
Hi @norman-abramovitz, thanks for raising this. We have stories in our backlog to review support for the small footprint runtime (install-only for now): https://www.pivotaltracker.com/story/show/151927918 and we've prioritised this work.

**Comment by abbyachau** [comment]
Hi @norman-abramovitz thanks again for creating this. I'm closing this issue because the team's roadmap no longer includes this epic. Please do not hesitate to reach out should you have any questions/feedback. Thanks.
