### ISSUE TITLE
"SMTP TLS configuration mismatch: Configured to use TLS over SMTP, but the mail server does not support the "STARTTLS" extension."

### ISSUE THREAD

**Issue by mgunter-pivotal** [pivotal-cf/pcf-pipelines#233]
New Param needed for the the "TLS checkbox" on the Notifications section of ERT config.  In the above Error, the TLS checkbox needs to be set to "false" (default is true).

**Comment by abbyachau** [comment]
Hi @mgunter-pivotal, thanks for raising this issue. Which IAAS are you on please? Thanks.

**Comment by mgunter-pivotal** [comment]
vSphere Director 1.12.4
ERT 1.12.6

**Comment by abbyachau** [comment]
Thanks @mgunter-pivotal, we've prioritised this issue. As discussed, we'll try to get it in v22. Thanks.

**Comment by abbyachau** [comment]
Hi @mgunter-pivotal, we've just published v22 which includes this feature request. Please do not hesitate to create a new issue should you have any feedback. Thanks.
