### ISSUE TITLE
Switch to S3 Signature v4 for AWS

### ISSUE THREAD

**Issue by mrbuk** [pivotal-cf/pcf-pipelines#234]
At the moment we use S3 Signature v2 in the [PCF Pipelines](https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/configure-ert/task.sh#L275) for the S3 configuration of ERT. See 

S3 Signature v2 is unfortunately not supported with new regions (e.g. _eu-central-1_). Only S3 Signature v4 is supported there and that one is supported by all regions according to [AWS docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/auth-request-sig-v2.html). It seems that switching to v4 only has advantages.

Additionally it should be mentioned that the [configure-director](https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/aws/tasks/config-director/task.sh#L48) task is already using v4.

**Comment by abbyachau** [comment]
Hi @mrbuk thanks closing this issue as we've merged https://github.com/pivotal-cf/pcf-pipelines/pull/235. Please let us know if any feedback by creating a new issue. Thanks.
