### ISSUE TITLE
Why you don't use Application Gateway instead of Azure LB?

### ISSUE THREAD

**Issue by kamoljan** [pivotal-cf/pcf-pipelines#238]
Hi guys!

Any reason why you don't use Azure Application Gateway(AAG) instead of Azure Load Balancer (ALB)?
Or at least combination of both ALB & AAG, if you need L4.

AAG has support for SSL termination and other L7 securities.
Which makes life easier in Azure environment.

**Comment by abbyachau** [comment]
Hi @kamoljan, good speaking to you last week. Ops Manager will start supporting Azure Application Gateway with PCF 2.1. The pipelines can review adding this functionality then. Please let us know if any questions.

**Comment by kamoljan** [comment]
@abbyachau Thank you Abby!
