### ISSUE TITLE
Network Security Group is not attached to a LB of ops manager

### ISSUE THREAD

**Issue by kamoljan** [pivotal-cf/pcf-pipelines#239]
Hi guys

In Azure IaaS and the ops manager DNS has public IP (LB with public IP).
However, Network Security Group is not attached to that LB.

Best regards
Kamol

**Comment by abbyachau** [comment]
Thanks @kamoljan for raising this issue. We'll look into this.

**Comment by abbyachau** [comment]
Hi @kamoljan, we've just published [v22](https://github.com/pivotal-cf/pcf-pipelines/releases/tag/v0.22.0) which includes this feature request. Please do not hesitate to create a new issue should you have any feedback. Thanks.

**Comment by kamoljan** [comment]
@abbyachau thank you very much!
