### ISSUE TITLE
How-To Ignore or Fix vSphere SSL Certificate Failure

### ISSUE THREAD

**Issue by gaigaslab** [pivotal-cf/pcf-pipelines#242]
We have an untrusted certificate on our vSphere vCenter.  I can't get anyone to fix this.  This used to work, but now, we are getting an error: 'certificate signed by unknown authority'.

How can I specify to 'trust' certificate or add a trusted certificate to the job?

Here is the problem area:

deploy-opsman-vm 
09:36:44 Running deploy of OpsMgr VM task... 
09:36:44 {Properties redacted}
09:36:44 Importing OVA of new OpsMgr VM... 
09:36:44 Running govc import.ova -options=opsman_settings.json /tmp/build/39dbd1bf/pivnet-opsmgr/pcf-vsphere-1.12.5.ova 
09:36:44 govc: Post https://cvgapvxrvcs01.td.afg/sdk: x509: certificate signed by unknown authority

**Comment by abbyachau** [comment]
Hi @gaigaslab 

Which version of the pipelines are you using? We introduced new parameters [recently](https://github.com/pivotal-cf/pcf-pipelines/releases?after=v0.21.2-rc.5):
```
vcenter_insecure: CHANGEME         # vCenter skip TLS cert validation; enter `1` to disable cert verification, `0` to enable verification
vcenter_ca_cert: CHANGEME          # vCenter CA cert at the API endpoint; enter a value if `vcenter_insecure: 0`
```

which will allow you to enable/disable this setting.

**Comment by abbyachau** [comment]
Hi @gaigaslab, closing this issue because we've introduced parameters which would allow you to control vCenter cert verification. Please do not hesitate to reach out and create a new issue if you have any feedback or questions. Thanks.
