### ISSUE TITLE
NSX requires Monitor Port and Port

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/pcf-pipelines#246]
For any load balancer to be configured via C0, we need to be able to set the monitor port (required) and the service port (optional).  Since these can be different, we need to allow both to be set. Screen shot shows both a correct (manually done via cookbook) and incorrect (via pipeline) because the same port is used.

<img width="809" alt="screen shot 2017-12-05 at 6 32 14 pm" src="https://user-images.githubusercontent.com/30056870/33638541-b08e0874-d9f4-11e7-88e8-8ddc293cd61f.png">

**Comment by abbyachau** [comment]
Hi @agregory999 please could you provide more information here, how we can repro the issue you've seen? Do you remember which version of the pipelines you were using when you noticed this issue?

**Comment by forddonald** [comment]
As per the docs, thus in the NSX cookbook, monitoring of gorouters should be done on port 8080 using a GET /health call. If a Service Monitoring definition is created without specifying both port and monitoring port, the primary port number will be used for both.

**Comment by abbyachau** [comment]
Hi @forddonald thanks for clarifying. It sounds like we need another param for the pools, i.e. `router_nsx_lb_monitoring_port` for each of the components.

**Comment by forddonald** [comment]
I'm curious how PCF Pipelines is involved with setting these NSX parameters at all. I seem to remember that PCF Pipelines doesn't setup NSX ESG features at all, only toggles on/off BOSH capability to build security groups and populate pools.

**Comment by agregory999** [comment]
The pipelines allow for the creation of the NSX security groups, and allow the ERT to dynamically update (via BOSH) the member pools.  In our pipelines we defined the standard ones for web, SSH, and TCP, and then an additional one for MySQL and HTTPS traffic.  These last 2 seem to use different ports for monitoring than service.

**Comment by agregory999** [comment]
@forddonald Does the (port = monitor port) rule change if we terminate SSL at NSX, HA, or Router?  Wasn't sure if the cookbook allowed each.

**Comment by forddonald** [comment]
The monitors in ESG are just definitions for how to monitor a thing. In the cookbook we say to make new definitions for how to monitor PCF http things and tcp things. NSX comes with a few pre-defined as well. How you then terminate or pass traffic thru the LBs is separate from these monitor definitions.

**Comment by abbyachau** [comment]
Thanks, I've reached out to @agregory999 for more information regarding their initial set up.

**Comment by abbyachau** [comment]
@agregory999 closing this issue as discussed. Thanks.
