### ISSUE TITLE
Question about compatibility matrix 

### ISSUE THREAD

**Issue by David-Pivotal** [pivotal-cf/pcf-pipelines#249]
Could you advise whether pcf-pipelines v21 is compatible with `Opsman 1.10 and ERT 1.10`?

I checked `Compatibility Matrix` in README.md which writes `pcf-pipelines v21 is compatible with Opsman 1.12 and ERT 1.12` but there is no information about `Opsman 1.10 and ERT 1.10`.

**Comment by abbyachau** [comment]
Hi @David-Pivotal the install-pcf pipeline is not compatible with PCF 1.10. We do not support backward compatibility but you could try release `v0.15.1`, which is the last known version to work with PCF 1.10. However, we cannot guarantee this version will work as expected, and unfortunately cannot provide support if it does not. Please do not hesitate to reach out directly if you have any questions. Thanks.

**Comment by David-Pivotal** [comment]
@abbyachau Got it. Thank you for the explanation and please feel free to close this ticket.
