### ISSUE TITLE
[Azure] Ops manager endpoint is open to the world with public IP

### ISSUE THREAD

**Issue by kamoljan** [pivotal-cf/pcf-pipelines#252]
Maybe need to restrict with private IP or with Network Security Group?

**Comment by abbyachau** [comment]
Hi @kamoljan, thank you for creating this issue. Since we've completed the story to make the Ops Manager IP [configurable](https://github.com/pivotal-cf/pcf-pipelines/pull/271), I plan on marking this issue as done. Please let me know if any issues with that. Thanks.

**Comment by kamoljan** [comment]
@abbyachau thank you!
