### ISSUE TITLE
The Script gen_ssl_certs.sh creates certificate requests with untrustworthy SHA1 signatures.

### ISSUE THREAD

**Issue by generalinterest** [pivotal-cf/pcf-pipelines#254]
The SHA1 certificates produced are now rejected by Google Chrome browsers.

The script should update the CSR to specify SHA256 signatures.

Line 49
openssl x509 -req -days 36500 -sha256

**Comment by abbyachau** [comment]
Hi @generalinterest thanks for raising this issue. Prioritised for engineer review.

**Comment by abbyachau** [comment]
Hi @generalinterest could you let us know which version of the pipelines you are using, and how you've obtained the release (via PivNet or GitHub?)? thanks. Please also let us know which version of PCF you are trying to install. Thanks.

**Comment by abbyachau** [comment]
Hi @generalinterest, thanks, we've updated the pipelines with a fix - which will be included in the next release of the pipelines. Please let us know if you have any feedback by opening a new issue. Thanks.
