### ISSUE TITLE
ERT Tile 1.12.9 metadata issue causing pcf-pipeline to fail

### ISSUE THREAD

**Issue by simmyxavier** [pivotal-cf/pcf-pipelines#260]
Seeing that we have an issue with the metadata.yml file for ERT 1.12.9. there is a typo and it says srt instead fo ert and hence the “Upload Stemcell” is failing. Logs below for reference.

2018/01/02 20:28:20 Extracting 'metadata/cf.yml' from '/tmp/build/2a19969b/pivnet-product/cf-1.12.9-build.3.pivotal
/tmp/build/2a19969b/pivnet-product/srt-1.12.9-build.3.pivotal'...
2018/01/02 20:28:20 open /tmp/build/2a19969b/pivnet-product/cf-1.12.9-build.3.pivotal
/tmp/build/2a19969b/pivnet-product/srt-1.12.9-build.3.pivotal: no such file or directory

**Comment by abbyachau** [comment]
Hi @simmyxavier thanks for raising this issue. We are looking into this.

**Comment by oozie** [comment]
@simmyxavier what version of `pcf-pipelines` have you ovserved this behavior with?

**Comment by simmyxavier** [comment]
The issue was observed in all the versions of pipelines we ran in our environment. Have tested on v0.8.0 and v0.14.1 and the same results

Thanks
Simmy

**Comment by oozie** [comment]
@simmyxavier can you please test with the latest available version on pivnet `v0.21.1`
(v14 is from May of 2017, way before SRT was a thing).

**Comment by oozie** [comment]
We're going to close this issue now, please reopen if the problem persists.
