### ISSUE TITLE
Look forward to PCF-pipelines compatible with PCF 2.0 

### ISSUE THREAD

**Issue by David-Pivotal** [pivotal-cf/pcf-pipelines#262]
Hi Team,

Do we have a plan to publish a new release to be compatible with PCF 2.0?
PCF 2.0 was released several days ago so it would be great if we could have a new release running on it. This can automate the setup of PCF 2.0 and saves lots of time.

Regards,
David

**Comment by abbyachau** [comment]
Hi @David-Pivotal, thanks yes we plan to support 2.0. We've already done a significant amount of work toward this effort. We plan on publishing v22 soon (which will support 1.12.x). And will then prioritise AWS and GCP support for PCF 2.0 with vSphere, Azure, and OpenStack to follow soon after. Please do not hesitate to get in touch directly should you have any questions.

**Comment by David-Pivotal** [comment]
Hi @abbyachau Thanks for your comments and good to know we are on the way to support PCF 2.0!
