### ISSUE TITLE
all the opsman tasks has input of client_id/client_secret/username/password but only client_id is used during call

### ISSUE THREAD

**Issue by sapient007** [pivotal-cf/pcf-pipelines#263]
notes (in params file) indicate that only client_id/client_secret OR username/password combo will be needed but one needs to tweak all the tasks to make that actually work since client_id combo inserted first. Suggest to clarify the notes. 

from wait for opsman task 

"om-linux \
  --target "https://${OPSMAN_DOMAIN_OR_IP_ADDRESS}" \
  --skip-ssl-validation \
  --client-id "${OPSMAN_CLIENT_ID}" \
  --client-secret "${OPSMAN_CLIENT_SECRET}" \
  --username "${OPSMAN_USERNAME}" \
  --password "${OPSMAN_PASSWORD}" \
  apply-changes \
  --ignore-warnings"

**Comment by abbyachau** [comment]
Hi @sapient007 thanks for the feedback. We plan on removing these variables for the install-pcf pipeline (and keeping them for the upgrade scenarios) but the next version of the release will include these params unfortunately for the install scenarios. Can you clarify the issue you are seeing? You note that only client_id is used, do you mean that the client_id is invoked first? We will update the README with clarifying notes. Thanks.

**Comment by sapient007** [comment]
client_id will be invoked first per current script. I don't believe --username and --password is even used since it is passed in after --client_id and --client-secret

**Comment by abbyachau** [comment]
Hey @sapient007, the params have been updated to clarify usage, based on your feedback. If the client_id and client_secret is not provided, (left blank in the params), the task will then use opsman_admin_username/opsman_admin_password. Please let me know if I've missed anything here. Thanks.

**Comment by sapient007** [comment]
found the code in om tool which checks whether client_id is ""

this issue is resolved
