### ISSUE TITLE
Inconsistent/ unconfigurable sys/apps domains.

### ISSUE THREAD

**Issue by srbry** [pivotal-cf/pcf-pipelines#267]
Currently system domain is hardcoded to be: `sys.${pcf_ert_domain}`, this is a configurable value in ERT and users may want to use `platform.${pcf_ert_domain}` or something else of their choosing. This is a particular issue for users that previously configured ERT manually and do not want to change domains so that they can consume pcf-pipelines.

Unfortunately the story with the apps domains appears to be worse. It is hardcoded in some places to be `cfapps.{pcf_ert_domain}`. For example: https://github.com/pivotal-cf/pcf-pipelines/blob/491a7e5e5284d0ee1ecbf10197b9de97d300e338/install-pcf/azure/tasks/cats/run-cats.sh#L67 and https://github.com/pivotal-cf/pcf-pipelines/blob/30d5b752ae17e274b170c9c94ce993b543f17b9c/install-pcf/aws/terraform/route53.tf#L11

However in some places it is configurable: https://github.com/pivotal-cf/pcf-pipelines/blob/7fe5bc17f5897e634ab33d8978828a4f3cd69ea8/install-pcf/azure/params.yml#L84

This makes it very easy to setup an environment that cannot work.

Some customers may also have an objection to using `cfapps` from a security perspective as it also exposes that the domain is being used for `cf`.

Can we make both domains configurable and use a single source of truth for the configuration?

**Comment by abbyachau** [comment]
Hi @srbry, thank you for reaching out. Scheduling for engineering review.

**Comment by abbyachau** [comment]
Hi @srbry, thanks, the team's implemented a fix for the issue you have raised. We will be releasing pcf-pipelines v24 with this fix at some point soon. Thanks again.
