### ISSUE TITLE
Why opsman IP is hardcoded?!!

### ISSUE THREAD

**Issue by kamoljan** [pivotal-cf/pcf-pipelines#269]
https://github.com/pivotal-cf/pcf-pipelines/blob/f8e5b5793729278d9c9a5c13d2c8d4d9be4d640a/install-pcf/azure/terraform/c0-azure-base/ops_manager.tf#L16

**Comment by abbyachau** [comment]
Hi @kamoljan, thanks for this and your pull request. Prioritised for engineer review.

**Comment by kcboyle** [comment]
@kamoljan Thanks for the issue. Do you have a use case to make this address configurable?

**Comment by kamoljan** [comment]
@kcboyle yes.
You have params to configure [IPs](https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/azure/params.yml#L51-L67),
if you change it (e.g. from `192.168.0.0/20` to `10.0.0.0/20`), the pipeline deployment will fail.

Also, we need this address spaces to be configurable to avoid IP clashing in vnet peering (Azure case) or VPN connections.

**Comment by abbyachau** [comment]
Hi @kamoljan, thanks, the team's implemented a fix for the issue you have raised. We will be releasing pcf-pipelines v24 with this fix at some point soon. Thanks again.
