### ISSUE TITLE
deploy-opsman-vm task is failing when trying to shutdown the old opsman VM

### ISSUE THREAD

**Issue by gokeefe** [pivotal-cf/pcf-pipelines#274]
## Issue

release: tag v0.22.0
pipelines: upgrade-ops-manager
iaas: vsphere
PCF: 1.11

## Context

The `upgrade-ops-manager` pipeline seems to be failing because the `govc find` command of the `deploy-opsman-vm` task (line 68 of task.sh) is returning multiple results even though the `-guest.ipAddress` argument should be returning only one match. The error also indicates that subsequent govc commands are not handling spaces in the ipath.

### Expected result

`deploy-opsman-vm` task should successfully shut down the old ops manager VM and power on the new one.

### Current result

```
# show that GOVC_RESOURCE_POOL is defined
$ echo $GOVC_RESOURCE_POOL | wc -c
37
# show that OPSMAN_IP is defined
$ echo $OPSMAN_IP | wc -c
13
# demonstrate that govc find is returning more than one result
$ govc find ${GOVC_RESOURCE_POOL} -type m -guest.ipAddress ${OPSMAN_IP} -runtime.powerState poweredOn | wc -l
22
```

#### Error in concourse that appears to show that following commands are not handling spaces correctly (full ipath should be /VB2/vm/Discovered virtual machine/<vmname>)

    govc: device '/VB2/vm/Discovered' not found

#### in shell, define OPSMAN_IP and GOVC environment variables
GOVC_USERNAME=<redacted>
GOVC_PASSWORD=<redacted>
GOVC_DATACENTER="VB2"
GOVC_CLUSTER=<redacted>
GOVC_RESOURCE_POOL=<redacted>
GOVC_DATASTORE=<redacted>
GOVC_URL=<redacted>
OPSMAN_IP="10.x.x.x"

#### run `govc find` command from deploy-opsman-vm task.sh
govc find ${GOVC_RESOURCE_POOL} -type m -guest.ipAddress ${OPSMAN_IP} -runtime.powerState poweredOn

Results may show more than one result, even though other results either have a different guest IP address, or return no guest IP address (likely due to VMware tools not running or not installed)

## Possible Fix

Maybe revert commit d7897be827c85a2f3c64f5bcfc196d32a4fef70b, or figure out why the deploy-opsman-vm task was rewritten in that commit? The `opsman_path` variable created on line 68 using the `govc find` appears to only be used in the following two lines to disconnect and power off the old ops manager VM, and the old command(s) appear to work just fine, so I don't see any obvious reasons why the this change was commited.

**Comment by abbyachau** [comment]
Hi @gokeefe, thanks for submitting this. Prioritised for engineering review.

**Comment by kcboyle** [comment]
@gokeefe thank you for reporting. This does look like a problem. To help us find a better solution, could you please provide the output of 
```
$ govc find ${GOVC_RESOURCE_POOL} -type m -guest.ipAddress ${OPSMAN_IP} -runtime.powerState poweredOn
```
(without the `wc -l`)?

Thank you!

**Comment by gokeefe** [comment]
Not sure this is going to be particularly useful... it does return the correct vm for ops manager, but it also returns a bunch more.

# govc find ${GOVC_RESOURCE_POOL} -type m -guest.ipAddress ${OPSMAN_IP} -runtime.powerState poweredOn
/VB2/vm/PivotalCF_DEV-SIT/PivotalCF/lxapp-d-pcfops01-1.11.21
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>
/VB2/vm/Discovered virtual machine/<redacted-vm-name>

**Comment by abbyachau** [comment]
Hi @gokeefe many thanks for creating this issue. We've applied a fix and will be releasing it in v23.1 soon.

**Comment by gokeefe** [comment]
Hi, I've reviewed the commit that references this issue and it appears it may resolve the error when the resource path contains spaces, but it does not touch the issue of "govc find" returning multiple VMs even when the -guest.ipAddress argument is included. govc seems to be ignoring the guest.ipAddress argument and/or returning unexpected results when the guest.ipAddress argument is included.

In my case, $old_opsman_path will contains the paths to multiple VMs and presumably any govc command that references $old_opsman_path will fail.

**Comment by gokeefe** [comment]
This appears to have been a bug in govc that has been fixed.

https://github.com/vmware/govmomi/issues/1089
