### ISSUE TITLE
Configuring external db for credhub

### ISSUE THREAD

**Issue by making** [pivotal-cf/pcf-pipelines#277]
pcf-pipelines does not seem to configure external db for credhub that was [introduced since PAS 2.0](http://docs.pivotal.io/pivotalcf/2-0/customizing/aws-er-config-terraform.html#credhub).

https://github.com/pivotal-cf/pcf-pipelines/blob/v0.23.0/install-pcf/aws/pipeline.yml#L304-L328

## Issue

* v0.23.0 (PAS 2.0.3)
* install-pcf
* AWS

## Context

I tried to install PAS 2.0 manually and failed due to credhub + external db.
I was wondering why this didn't occur in pcf-pipeline and found that was not configured.

**Comment by abbyachau** [comment]
Hi @making, we released v23 with only support for the internal db for CredHub. Please see release [notes](https://github.com/pivotal-cf/pcf-pipelines/releases. We plan on adding support for the external db at a later date.

**Comment by making** [comment]
@abbyachau I wasn't aware of that. Thanks!

**Comment by abbyachau** [comment]
@making no problem, thanks for reaching out.
