### ISSUE TITLE
NAT VM Sizing

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/pcf-pipelines#279]
Thanks for submitting an issue to pcf-pipelines. To help us triage the issue, please fill out the following form as much as you can:

## Issue

NAT VM sizes may be larger than necessary

## Context

I typically shut down NAT VMs and change to micro, and they work just fine.  Perhaps consider reducing the size, for IAAS cost purposes.

### Expected result

Still Works.

### Current result

[Describe what you currently experience from this process]

## Steps to Reproduce

[Detail the process in which we can to find and recreate the issue]

## Possible Fix

[Not obligatory, but suggest fixes or reasons for the bug]

## Logs and Screenshots

[If you have logs or screenshots you can share with us, please do!]

**Comment by forddonald** [comment]
PCF Pipelines build PCF installations with the intention of being prod-ready. Which IaaS does this issue relate to?

**Comment by agregory999** [comment]
Hi Ford -

This is on GCP. If the NAT VMs really need 4 cores and 15Gb of RAM (and 3 total), then we can close it out. I can adjust what my testbed uses to be micro after the install is complete..

-Andrew

Andrew Gregory
Senior Platform Architect, New England
+1 617-529-0749 | agregory@pivotal.io <mailto:agregory@pivotal.io>



Transforming how the world builds software.

**Comment by abbyachau** [comment]
Hi @agregory999 thanks, closing this issue out.
