### ISSUE TITLE
GCP: Services Network should not be service_network

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/pcf-pipelines#281]
Thanks for submitting an issue to pcf-pipelines. To help us triage the issue, please fill out the following form as much as you can:

## Issue

The Service Network shouldn't have the services network checkbox enabled, as that is only for dynamic services.
 
## Context

Installing tiles will be incorrect later, as the services network will not show up. OpsMan only shows networks without the checkbox for main tile config.

### Expected result

[Describe what you would expect to have resulted from this process]

### Current result

[Describe what you currently experience from this process]

## Steps to Reproduce

[Detail the process in which we can to find and recreate the issue]

## Possible Fix

Look for this variable and change it so it is a static false, unless there is a need to make it a varaible.
 Check the other IAAS to see what they do - it was correct on AWS.. services_network_is_service_network

## Logs and Screenshots

[If you have logs or screenshots you can share with us, please do!]

**Comment by abbyachau** [comment]
Thanks @agregory999. Prioritizing for eng work.

**Comment by abbyachau** [comment]
Thanks again for creating this issue @agregory999. The fix will be in the next release.
