### ISSUE TITLE
Credhub Encryption key fails if unquoted string of digits

### ISSUE THREAD

**Issue by agregory999** [pivotal-cf/pcf-pipelines#282]
Thanks for submitting an issue to pcf-pipelines. To help us triage the issue, please fill out the following form as much as you can:

## Issue

Might we a yml thing, but with a string of 20 digits fails with an error:

51
{"errors":{"base":["undefined method `length' for 12345678901234567000:Bignum"]}}
0

## Context

[Add more details about how this issue is affecting your use of the product]

### Expected result

[Describe what you would expect to have resulted from this process]

### Current result

If you start the string of numbers with a character, the issue disappears

## Steps to Reproduce

Use 12345678901234567890 with no quotes.  I didn't actually try quotes, but if they would help,

## Possible Fix

I didn't actually try quotes, but if they would help, update the params file with a comment.

## Logs and Screenshots

[If you have logs or screenshots you can share with us, please do!]

**Comment by zmb3** [comment]
This is just a yml thing. Quotes generally aren’t required for strings, but if you’re providing a number with no other characters in it yml treats it as such.

Using numbers only is not great practice for an encryption key, but that’s a separate point.

**Comment by agregory999** [comment]
Just dumb luck in trying to count to 20 digits - probably a simple comment or lesson learned in the readme would suffice....

Aside from that it all worked.

-Andrew

Andrew Gregory
Senior Platform Architect, New England
+1 617-529-0749 | agregory@pivotal.io <mailto:agregory@pivotal.io>



Transforming how the world builds software.

**Comment by abbyachau** [comment]
Hi @agregory999, thanks. Seems unnecessary to update the params in this case as most folks will not be using a numbers-only key. I don't want to add additional comments to the param.yml unless it is essential (trying to keep the params.yml from being too cluttered). Thanks!
