### ISSUE TITLE
upgrade-ops-manager pipeline on GCP does not resize default disk

### ISSUE THREAD

**Issue by cpage-pivotal** [pivotal-cf/pcf-pipelines#285]
## Issue

Running pcf-pipeline v0.23.0 on GCP. Using the upgrade-ops-manager pipeline to upgrade from version 2.0.0 to 2.0.5 of Ops Manager. The replacement VM starts up with the correct version of Ops Manager installed, but the attached disk only has a default storage allocation of 5G

## Context

Next steps in the pipeline predictably fail, because there is not enough available storage to unpack and install software.

### Expected result

New Ops Manager VM should have appropriate levels of attached storage (e.g. 50-100G) 

### Current result

New Ops Manager VM only has 5G of attached storage

**Comment by abbyachau** [comment]
Thanks @cpage-pivotal, prioritising for engineer review.

**Comment by abbyachau** [comment]
Hi @cpage-pivotal thanks for creating this issue. We've introduced a new param `pcf_opsman_disk_size_in_gb` which allows you to configure the Ops Man disk size before you run the upgrade. If the param is left blank, the original disk size will be honoured. This fix will be in `v23.1`. If you have any questions/feedback, do not hesitate to reach out. Thanks.
