### ISSUE TITLE
config-opsmgr job still passes if network is not correctly set.

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/pcf-pipelines#29]
This should fail out, however job shows green.

```{}
Configuring networks...
Status: 422 Unprocessable Entity
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Thu, 27 Apr 2017 16:07:57 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 043b0400-32af-478a-91cf-569714e40c44
X-Runtime: 0.175094
X-Xss-Protection: 1; mode=block
{
  "errors": [
    "Networks There is an error on a network.",
    "Networks DEPLOYMENT: Subnets : [0] Availability zone references can't be blank",
    "Availability zones This infrastructure requires an availability zone",
    "Availability zones cannot find availability zone with name PCF"
  ]
}```

**Comment by ryanpei** [comment]
@haydonryan is this the same as issue #30 ?

**Comment by haydonryan** [comment]
No - #30 is a consequence of this job passing when it shouldn't have

**Comment by ryanpei** [comment]
i see, so you'd like it to fail here on this job instead of a later job, correct?

**Comment by haydonryan** [comment]
@ryanpei Exactly, I'd expect the step that fails to cause that job to fail, not pass even though the task failed and then fail on the next job... if that makes sense.

**Comment by krishicks** [comment]
We have a `-e` on the task.sh that runs this; if it succeeds then we can't know that it has failed. This problem should be raised with the maintainers of `om`: https://github.com/pivotal-cf/om/issues/new
