### ISSUE TITLE
Fix example documentation for opsman_domain_or_ip_address in params.yml

### ISSUE THREAD

**Issue by brunograz** [pivotal-cf/pcf-pipelines#291]
Version: v0.23.0/master

We faced a minor issue using the pipeline to upgrade Ops Manager on VSphere - but it likely affects Openstack and others. 
The example given for `opsman_domain_or_ip_address`  in [params.ym](https://github.com/pivotal-cf/pcf-pipelines/blob/v0.23.0/upgrade-ops-manager/vsphere/params.yml#L27) includes _http://_ or _https://_ in case a domain is used, these have to be removed as tasks that uses this parameter already assumes every connection is done via https. [Task example](https://github.com/pivotal-cf/pcf-pipelines/blob/v0.23.0/tasks/wait-opsman-clear/task.sh#L32).

If _https://_ is included in the domain name, tasks may fail as it tries to send a POST request to:
- `https://https/uaa/oauth/token`

**Comment by abbyachau** [comment]
Hi @brunograz, thanks for raising this. We've updated all the [params](https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-ops-manager/vsphere/params.yml) as advised.
