### ISSUE TITLE
(initial pcf deploy) If opsdir configuration is incomplete then the apply changes step loops constantly.

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/pcf-pipelines#30]
(for example if the network failed to be updated in the previous step)

**Comment by ryanpei** [comment]
@haydonryan which PCF version and which IaaS did you use this with?

**Comment by haydonryan** [comment]
vSphere, deploy - using ops mgr 1.10.4 haven't gotten up to the ERT component.

**Comment by krishicks** [comment]
This is something that should be fixed by the previous job failing, which should be raised as an issue on `om`: https://github.com/pivotal-cf/om/issues/new
