### ISSUE TITLE
Link for Pivotal Network release of pcf-pipelines

### ISSUE THREAD

**Issue by bruxelles86** [pivotal-cf/pcf-pipelines#300]
Hi. I'm quite possibly missing something simple here, but the link to the Pivotal Network release of `pcf-pipelines` seems to be broken, and I can't find the release when searching around network.pivotal.io myself. Does the readme need updating or am I looking in the wrong place?

Thanks.

**Comment by abbyachau** [comment]
Hi @bruxelles86 the Pivotal Network release of pcf-pipelines are restricted to specific user groups only. I need to add your details to grant you permission. I will reach out via email to gather this information.

**Comment by abbyachau** [comment]
Hi @bruxelles86 closing this issue as we've resolved this now. Thanks.
