### ISSUE TITLE
Required a pipeline  for updating more then on tile.

### ISSUE THREAD

**Issue by vasanthg1210** [pivotal-cf/pcf-pipelines#302]
Hi Team,

I am not facing any issue. Its just an request for updating more then one tile using concourse.

I have done with updating single tile "https://github.com/pivotal-cf/pcf-pipelines/tree/master/upgrade-tile"
with little modification. Able to update the tile with Apply changes.

Now required to update more then one tile. for example 2 tile. please share me the pipeline and parameter for the same.

Thanks,
Vasanth

**Comment by vasanthg1210** [comment]
I created a pipeline. but getting error.
"fly validate-pipeline --config multi-tile-pipeline.yml
could not resolve template vars: yaml: did not find expected <document start>"

groups: []

resource_types:
- name: pivnet
  type: docker-image
  source:
    uri: https://hub.docker.com/r/pivotalcf/pivnet-resource
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: master
 
- name: pivnet-product
  type: pivnet
  source:
    api_token: xxxxx
    product_slug: p-mysql
    sort_by: semver

- name: pivnet-product1
  type: pivnet
  source:
    api_token: xxxxx
    product_slug: p-rabbitmq
    sort_by: semver
	
jobs:
- name: upload-tile
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product
    params:
      product_slugs: p-mysql
      trigger: true

  - task: upload-tile-and-stemcell
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: aws
      OPSMAN_DOMAIN_OR_IP_ADDRESS: xxxxx
      OPS_MGR_USR: xxxxx
      OPS_MGR_PWD: xxxxx
      PIVNET_API_TOKEN: xxxxx

- name: upload-tile
  max_in_flight: 1
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-product1
    params:
      product_slugs: p-rabbitmq
      trigger: true

  - task: upload-tile-and-stemcell
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      IAAS: aws
      OPSMAN_DOMAIN_OR_IP_ADDRESS: xxxxx
      OPS_MGR_USR: xxxxx
      OPS_MGR_PWD: xxxxx
      PIVNET_API_TOKEN: xxxxx

**Comment by abbyachau** [comment]
Hi @vasanthg1210 please review our repo [page](https://github.com/pivotal-cf/pcf-pipelines#deploying-and-managing-multiple-pipelines) for more information about managing updating more than one tile. Thanks.
