### ISSUE TITLE
Legacy token for pivnet_token?

### ISSUE THREAD

**Issue by brunograz** [pivotal-cf/pcf-pipelines#303]
We are using the upgrade-opsmanager pipeline and the job download-stemcells is failing because it could not login to Pivotal network. Currently we are using the UAA API token for this task but I have tried with the Legacy token and it seems to be working. 
Is this the expected behavior?

Version: 0.23.0

PS: Apologies for creating an empty issue at first, pressed enter by mistake :)

**Comment by abbyachau** [comment]
@brunograz thanks for creating this issue. Please could you confirm 
- the version of the pipelines you are using
- the version of PCF you are upgrading
- which IAAS you are on
- are you using the "new" Pivotal Network token? 
- please could you provide the error log as well.

Thanks!

**Comment by brunograz** [comment]
- the version of the pipelines you are using
v0.23.0

- the version of PCF you are upgrading
1.12.x

- which IAAS you are on
Vsphere

- are you using the "new" Pivotal Network token?
I recently joined Pivotal network and I'm not sure what "new" means in this case. I was using the "UAA API token" provided in my account settings. This token was returning the error. In that same page there was another token - Legacy token. That one worked fine.

- please could you provide the error log as well
![image](https://user-images.githubusercontent.com/8091247/37148558-31763636-22cb-11e8-89fb-dcd3de7a7896.png)
That's all it returns.

**Comment by abbyachau** [comment]
Hi @brunograz thanks for reporting the issue. The pipelines do not support the new UAA API tokens at the moment. We only support the Legacy tokens, as you've found out. I've updated the [documentation](https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-ops-manager/vsphere/params.yml#L29) to reflect this to avoid confusion. Thanks again.

**Comment by brunograz** [comment]
Hi @abbyachau,
Thanks for updating the documentation.
