### ISSUE TITLE
Configuring IaaS failed wtih EOF error

### ISSUE THREAD

**Issue by budaozhao** [pivotal-cf/pcf-pipelines#309]
Hi,

I deployed an ops manager (v 2.0 build 255). I am trying to configure the Iaas and directory by running the following command:

_om -k -t https://ops_manager_vm_ip -u admin -p '****' configure-bosh --iaas-configuration "$iaas_configuration" --director-configuration "$director_config"_

where iaas_configuration is something like:
_{
  "vcenter_host": "192.168.***.***",
  "vcenter_username": "***",
  "vcenter_password": "***",
  "datacenter": "my-dc",
  "disk_type": "thin",
  "ephemeral_datastores_string": "iscsi0",
  "persistent_datastores_string": "iscsi0",
  "bosh_vm_folder": "pcf_vms",
  "bosh_template_folder": "pcf_templates",
  "bosh_disk_path": "pcf_disk",
  "ssl_verification_enabled": false,
  "nsx_networking_enabled": false,
  "nsx_address": "",
  "nsx_username": "",
  "nsx_password": "",
  "nsx_ca_certificate": ""
}_ 
and director_config is like:
_{
    "ntp_servers_string": "*****.com",
    "post_deploy_enabled": true,
    "resurrector_enabled": false,
    "database_type": "internal",
    "blobstore_type": "local",
    "director_worker_count": 5,
    "director_hostname": ""
  }_

I got the below error:

**could not execute "configure-bosh": tile failed to configure: failed to POST form: Post https://ops_manager_vm_ip/infrastructure/iaas_configuration: EOF**

What might be wrong here? Where can I get detailed logs and debug this issue?

Thanks!

 Yong

**Comment by abbyachau** [comment]
Hi @budaozhao we only support users who have used the Pivotal Network release of the pipelines, or a tagged version on GitHub. Are you using the pipelines in such a way whereby you are making modifications - you should not need to run a api call manually, for instance. Thanks.

**Comment by budaozhao** [comment]
Thanks for the reply. I see. To your question, no, so I shouldn't ask question here. Sorry.  But are you aware of a place where general ops manager issues are discussed?  Thanks,

**Comment by abbyachau** [comment]
Hi @budaozhao are you a customer of PCF?

**Comment by budaozhao** [comment]
@abbyachau Strictly speaking I am not. I am from a partner company where we have access to and use pcf components to build a testing environment.  Thanks,

**Comment by abbyachau** [comment]
Hi @budaozhao do you have a Pivotal contact you can reach to help you get a hold of the internal teams? Can you tell me what the name of your partner company is?

**Comment by budaozhao** [comment]
@abbyachau I don't have a Pivotal contact. I would love to get connected if this is doable.  The company I was referring to was VMware.  For this particular issue I think I have done basic triaging with reasonable amount of details that I can provide if it helps identifying the problem.  Thanks regardless,

**Comment by abbyachau** [comment]
@budaozhao thanks - can you please provide an email address we can contact you on? I've checked your profile and was unable to locate one, thank you.

**Comment by budaozhao** [comment]
Sure. It's budaozhao@gmail.com  I just added this to my profile as well.  Thanks!

**Comment by budaozhao** [comment]
Just to give an update, based no my yesterday's debugging,  I suspected that it is more likely a client side issue, although I am not 100% sure at this point:  I enabled the nginx debug log on the ops manager.  Nginx got the first few requests (to GET some info and do authentication) generated from the om configure-bosh command. Those requests succeeded. But the server never got the POST request to update the config (POST /infrastructure/director_configuration HTTP/1.0). I could see from the nginx log that after a while the connection was shutdown by server.

**Comment by abbyachau** [comment]
Hey @budaozhao thank you! Do you have a work-related email you could pass through instead? Thanks!

**Comment by budaozhao** [comment]
It's yongl@vmware.com.  Thanks!

**Comment by abbyachau** [comment]
@budaozhao thank you, I'll get in touch with relevant emails. I've also just noticed that you are asking questions about the om [tool](https://github.com/pivotal-cf/om) - you could also try to create an issue in that repo as well. We'll be in touch.

**Comment by budaozhao** [comment]
Sure. I created an issue there and I am now working with them for further rootcausing. Thanks for your suggestion.
