### ISSUE TITLE
vSphere deploy fails in upload elastic runtime setep

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/pcf-pipelines#31]
This is due to the pivnet cli not being present in the fetch directory.

```
upload-er-tile:
chmod: missing operand after '+x'
Try 'chmod --help' for more information.
```
I'm currently investigating this too as it's a blocker for me.

**Comment by wrast** [comment]
This is due to issue #25. To workaround temporarily, look at that issue and fix the `globs` line.

**Comment by haydonryan** [comment]
Perfect thanks - i Just discovered that too... you beat me to it!
