### ISSUE TITLE
cf cli is not an executable in pcfnorm/rootfs docker image

### ISSUE THREAD

**Issue by pivotal-jleung** [pivotal-cf/pcf-pipelines#311]
Thanks for submitting an issue to pcf-pipelines. To help us triage the issue, please fill out the following form as much as you can:

## Issue
Buildpack pipeline run with errors. It is due to the cf command in the pcfnorm/rootfs docker image. I am not sure filing the issue here is a right place.

## Context
Buildpacks cannot be upgraded

### Expected result
Buildpacks pipeline to be completed without error

### Current result
Buildpacks pipeline failed at stage-binary-buildpack and other stages. Something wrong with the /usr/local/bin/cf command.

## Steps to Reproduce
Run the pipeline at v0.23.1-rc.29

## Possible Fix
The /usr/local/bin/cf command in the pcfnorm/rootfs is not an executable file.

Run the following docker command to verify the /usr/local/bin/cf file and found that is a gzip file.
- docker run pcfnorm/rootfs file /usr/local/bin/cf
/usr/local/bin/cf: gzip compressed data, from Unix, last modified: Fri Mar  9 00:00:16 2018

**Comment by jtarchie** [comment]
Thanks for pointing it out. We are resolving it.

This is part of our migration to version the docker images with the correct dependencies.

**Comment by jtarchie** [comment]
We've corrected the issue with the docker image.

```
→ docker run -it pcfnorm/rootfs cf --version
cf version 6.35.1+bfbe5f0e8.2018-03-14
```

Concourse should automatically download the updated version. Things should Just Work™.

**Comment by abbyachau** [comment]
@pivotal-jleung closing this issue - please do not hesitate to reach out if you have any feedback. Thanks again.
