### ISSUE TITLE
upgrade-buildpacks pipeline does not show filename/version on running cf buildpacks after upgrading

### ISSUE THREAD

**Issue by dhoffi** [pivotal-cf/pcf-pipelines#314]
## Issue

after running `upgrade-buildpacks` pipeline.
and doing a `cf buildpacks`
the column under 'filename' is empty, so it is hard to determine the current version of upgraded buildpacks.

### Expected result

seeing the filename of the upgraded buildpack with its name as if I would have downloaded it from pivnet and ran a `cf update-buildpack` manually

### Current result

'filename' column of upgraded buildpacks is empty on a `cf buildpacks`

**Comment by dhoffi** [comment]
might be that the missing filenames only occur if there is an error while 'uploading' the buildpacks ... still investigating this

**Comment by abbyachau** [comment]
Thanks @dhoffi, let us know if you find this is still an issue.

**Comment by fredwangwang** [comment]
Closing this issue. If it is indeed still a problem, please reopen.
