### ISSUE TITLE
GCP: CloudSQL DB Tier is hardcoded to a value that is not supported for production

### ISSUE THREAD

**Issue by eamonryan** [pivotal-cf/pcf-pipelines#325]
## Issue

Using v0.23.1 on the `install-pcf` pipeline for GCP deploying latest PCF 2.0.x, found that the Google CloudSQL DB Tier chosen by the sql.TF script is hardcoded to a test level non-production size of `db-f1-micro`. 

https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/gcp/terraform/sql.tf#L11

This can cause issues as it is a shared GCP DB instance so is subject to noisy neighbours which can impact the ability to deploy (and did lately) and is not supported for production use or protected by the Google SLA.

See https://cloud.google.com/sql/pricing

`*Shared CPU machine types (db-f1-micro and db-g1-small) are not covered by the Cloud SQL SLA.`

## Context

Saw multiple failed `create-infrastructure` jobs as the DB was responding too slowly and failed to be created partway multiple times, varying depending (presumably) on GCP load of that CloudSQL instance type in that GCP region/zone at the time.

### Expected result

`pcf-pipelines` should default to a dedicated production-grade CloudSQL tier such as `db-n1-standard-1` and ideally externalise this as a pipeline variable so it could be user-configurable without forking `pcf-pipelines`.

### Current result

DB Tier always is set to `db-f1-micro` as you can see at https://github.com/pivotal-cf/pcf-pipelines/blob/master/install-pcf/gcp/terraform/sql.tf#L11

## Steps to Reproduce

Installing PCF 2.0.x to GCP using the v0.23.1 pipelines will result in a CloudSQL DB instance of tier `db-f1-micro`.

## Possible Fix

See "Expected result"

**Comment by pivotal-maya-kenedy** [comment]
The Google CloudSQL DB Tier will be user-configurable in the next release.  We've left the default value as `db-f1-micro` to ensure backwards compatibility.  Thank you!
