### ISSUE TITLE
Documentation Still Needs A Fix

### ISSUE THREAD

**Issue by jregehr** [pivotal-cf/pcf-pipelines#329]
Thanks for submitting an issue to pcf-pipelines. To help us triage the issue, please fill out the following form as much as you can:

## Issue

See [Issue 327](https://github.com/pivotal-cf/pcf-pipelines/issues/327) - I requested changes to the **Downloading PCF Pipelines** section, *and* the **Compatibility Matrix** section.

The **Compatibility Matrix** section still needs a fix - the matrix still contains duplicate data.

**Comment by calebwashburn** [comment]
Updated the documentation for both the matrix and link.  Thanks @jregehr
