### ISSUE TITLE
Docker image for tasks using latest om-linux

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/pcf-pipelines#331]
[As I wrote on the om-linux issues page](https://github.com/pivotal-cf/om/issues/161), I was wondering if Pivotal had (or would be willing to provide) a docker image for use with foundation-related Concourse tasks that contained the latest version of `om-linux`.

[It appears most tasks in this project use `pcfnorm/rootfs`](https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/config-ert/task.yml#L8), which is a docker image containing `om-linux-0.34` (The current release of `om` is `0.37`).

Obviously, if not, no big deal, but is there any interest in maintaining/using a docker image akin to `pcfnorm/rootfs` that has the latest version of `om` on it?

Thank you!

**Comment by kreutziger** [comment]
We are currently experiencing issues with the old OM version (0.34.) which is used in the image, as we run into a configuration problem:
```    
  started configuring director options for bosh tile
  finished configuring director options for bosh tile
  started configuring availability zone options for bosh tile
  could not execute "configure-director": availability zones configuration could not be applied: request failed: unexpected response:
  HTTP/1.1 422 Unprocessable Entity
  [...]
  {"errors":["AvailabilityZones with guids 1234567890abcdef are in use and not deletable"]}
  0
```

**Comment by aegershman** [comment]
I'm going to go with providing the released om binary as an input to my pipeline tasks. I think that'll be better in the long run 👍
