### ISSUE TITLE
'config-ert' error - routing_custom_ca_certificates param

### ISSUE THREAD

**Issue by elric392** [pivotal-cf/pcf-pipelines#337]
Using release v0.23.4 downloaded from PivNet.  Attempting install of PCF v2.1 on vSphere 6.5, running into error during 'config-ert' task on the pipeline.

![image](https://user-images.githubusercontent.com/31511398/41595842-36b3a09a-7396-11e8-8403-87f387a07931.png)

Not understanding why the error is popping up, as the 'routing_custom_ca_certificates' param is listed as optional in the params.yml.  I have not defined it in my params.yml file.

![image](https://user-images.githubusercontent.com/31511398/41595886-6b12fa3e-7396-11e8-8253-938624788a41.png)

**Comment by nbconklin** [comment]
@elric392 What is your configuration params file have for `ROUTING_CUSTOM_CA_CERTIFICATES` in params file?

Should be set to: 

```
ROUTING_CUSTOM_CA_CERTIFICATES: ""
```

**Comment by elric392** [comment]
In the 'params.yml' file .... I left it as the default.

_# Optional - these certificates can be used to validate the certificates from incoming client requests.
# All CA certificates should be appended together into a single collection of PEM-encoded entries.
routing_custom_ca_certificates:_ 

Which, when processed by Concourse, becomes .... 
       ROUTING_CUSTOM_CA_CERTIFICATES: ""

I did try specifically setting the param to "" .... but it behaved the same.

**Comment by nbconklin** [comment]
If this line is not present in your file this is what exposes this variable to `jq` https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/config-ert/task.sh#L137

**Comment by elric392** [comment]
I have not modified the pipeline from what I downloaded from PivNet, other than filling out the params file to pull values from Vault.

**Comment by jtarchie** [comment]
@elric392, I think the`ROUTING_CUSTOM_CA_CERTIFICATES` might actually be red herring. I wondering if the other params that you have provided are not properly escaped for the `bash` script that they are used in. This could be cause the `jq` invocation to not get the correct arguments.

For example, I see that the [`routing_tls_termination`](https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/config-ert/task.sh#L136) is not properly escaped in quotes. What value do you have for that in your YAML? Obviously that is something we should fix, too.

**Comment by elric392** [comment]
'routing_tls_termination' is blank in my YAML.

**Comment by elric392** [comment]
Okay, the 'routing_custom_ca_certificates' was a red herring.  The real issue was not defining ....

_routing_tls_termination_ and _frontend_idle_timeout_

Neither were defined by default with 'CHANGEME' as most of the 'required' params are ..... I apologize for my confusion.

**Comment by jtarchie** [comment]
No worries. Glad we could solves your issue. I'm going to close this as resolved! 👍
