### ISSUE TITLE
x509 Certificate Error during Stemcell download 

### ISSUE THREAD

**Issue by nwoike** [pivotal-cf/pcf-pipelines#339]
## Issue
Downloading stemcells using the `upload-product-and-stemcell` task started failing with x509: certificate signed by unknown authority.

Testing locally I am able to recreate this error message using pivnet-cli version `0.0.49`. I am unable to recreate this error using pivnet-cli version `0.0.51`.

**Error Message**
```
failed to make HEAD request: Head https://d13k9s5899twdr.cloudfront.net/product_files/Pivotal-CF/8fc30b89-3257-4e8c-ab84-f042a0b7a51c?(redacted): x509: certificate signed by unknown authority
```

## Possible Fix
Update the `pcfnorm/rootfs` image to pull the latest `pivnet-cli` (0.0.51) binary and publish it to Dockerhub.

**Comment by nbconklin** [comment]
Thank you for reporting. A fix for this issue has been released : https://github.com/pivotal-cf/pcf-pipelines/tree/v0.23.6

**Comment by nwoike** [comment]
Thanks! It looks like you have a CI task that adds the correct tag of your Docker image in tasks for the Pivnet releases. We pull releases directly from Github so task image tags default to `latest` (which is a few months old). Is this intentional or is it possible to add the image tag version to tasks in the Github releases as well?

**Comment by nwoike** [comment]
But you are still defaulting to latest if you pull your latest [Github release](https://github.com/pivotal-cf/pcf-pipelines/archive/v0.23.6.zip).

**tasks/upload-product-and-stemcell/task.yml**

```
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
...
```
