### ISSUE TITLE
Installing concourse link has 404 error

### ISSUE THREAD

**Issue by jasonbisson** [pivotal-cf/pcf-pipelines#340]
Thanks for submitting an issue to pcf-pipelines.
Please note that this repository will be officially deprecated soon.
New and better tools to replace this repo are under development.
While you are welcome to raise issues,
not every issue will be prioritized.

To help us triage the issue, please fill out the following form as much as you can:

## Issue

[Provide a quick introduction; please include the pcf-pipelines release you are using, which pipelines you are using (install, upgrade, etc), which IAAS, and the version of PCF you are trying to deploy]

Under Prerequisites the Installing Concourse link is not working and fly link is not working

## Context

[Add more details about how this issue is affecting your use of the product]

### Expected result

[Describe what you would expect to have resulted from this process]

### Current result

[Describe what you currently experience from this process]

## Steps to Reproduce

[Detail the process in which we can to find and recreate the issue]

## Possible Fix

[Not obligatory, but suggest fixes or reasons for the bug]

## Logs and Screenshots

[If you have logs or screenshots you can share with us, please do!]

**Comment by calebwashburn** [comment]
Broken links have been fixed.
