### ISSUE TITLE
Double "https://" scheme in CredHub Integration docs.

### ISSUE THREAD

**Issue by coreyti** [pivotal-cf/pcf-pipelines#353]
## Issue

The documentation for "Adding secrets to CredHub" have the following text:

> credhub api https://https://<concourse_host>:8844:8844 --ca-cert <(bosh int ./concourse-gen-vars.yml --path /concourse-tls/ca)

### Expected result

"https://https://" should be replaced with "https://".

**Comment by nbconklin** [comment]
this has been fixed in the documentation, thanks @coreyti
