### ISSUE TITLE
97.* Stemcells not found. When utilizing 2.3.* ERT.

### ISSUE THREAD

**Issue by sonmacharius** [pivotal-cf/pcf-pipelines#361]
https://github.com/pivotal-cf/pcf-pipelines/blob/d90a6f3de4e3e0bb363cbca9cb1c435d882d0629/create-offline-pinned-pipelines/pipeline.yml#L223

Concourse Output of "create-elastic-runtime-tarball"
`Downloading stemcell 97.19
Warning: The use of static Pivnet API tokens is deprecated and will be removed. Please see https://network.pivotal.io/docs/api#how-to-authenticate for details on the new UAA API Token mechanism.
Logged-in successfully
release not found for version: '97.19'
`

**Comment by fredwangwang** [comment]
```
Downloading stemcell 97.28
Warning: The use of static Pivnet API tokens is deprecated and will be removed. Please see https://network.pivotal.io/docs/api#how-to-authenticate for details on the new UAA API Token mechanism.
Logged-in successfully
2018/11/02 18:01:17 Downloading 'bosh-stemcell-97.28-vsphere-esxi-ubuntu-xenial-go_agent.tgz' to 'bosh-stemcell-97.28-vsphere-esxi-ubuntu-xenial-go_agent.tgz'
```

It is fixed in the commit: 5e8e3dbc5e77415defaef85338b09f35170e3b29
If you want to apply the fix now, you can take the commit and apply to your pipeline.
Otherwise, we are in the process of cutting a new release.

Thanks again for the issue report!
