### ISSUE TITLE
[vsphere] Enabling MySql backup does not work.

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/pcf-pipelines#37]
```cf 1.10.7-build.1 is already staged
SSL Configuration:...
Setting CF resources and properties...
configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 02 May 2017 01:58:38 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 5cc38bd6-0372-4057-9854-62725b462763
X-Runtime: 0.574899
X-Xss-Protection: 1; mode=block

cd
{"errors":{".properties.tcp_routing":["You can only change properties that are under the selected option"],".**properties.mysql_backups":["Value 'enable' does not match the select_value of a known option"]**}}
0

```

**Comment by ryanpei** [comment]
@haydonryan did you try enabling MySQL backups or TCP routing here? It looks like from the error message that you tried TCP routing. MySQL backups should be enable-able (configure `mysql_backups:` with values `s3` or `scp` and then specify the scp or S3 target for sending the backup files)

**Comment by haydonryan** [comment]
I took the default values for the params for the version I had.  I originally had TCP routing disabled, and then it complained about the ports field was not entered.  

Similarly with MySQL backups were enabled by default in the params (with that word) so I had to disable them.

**Comment by ryanpei** [comment]
We filed new issues for this #47 and #48. I will close this one out in favor of those.
