### ISSUE TITLE
Version of cf cli in pcfnorm/rootfs doesn't support buildpack stack association

### ISSUE THREAD

**Issue by djoyahoy** [pivotal-cf/pcf-pipelines#373]
## Issue

We are trying to update the `upgrade-buildpacks` pipeline by adding stack association. We need a cf cli that is capable of running `cf update-buildpack` with the `-s` flag. The `-s` flag allows us to disambiguate buildpacks that have the same name but are for different stacks.  

## Context

See the issue text above.

### Expected result

The pcfnorm/rootfs has a more recent version of the cf cli that has stack support.

### Current result

We get the following error from the cf cli when we run our promote task:
```
Incorrect Usage: unknown flag `s'
```

## Steps to Reproduce

1. `docker run -it pcfnorm/rootfs:latest bash`
2. `cf version` -> reports an older version.
3. `cf update-buildpack` -> help text does not include the `-s` flag.

## Possible Fix

Rebuild and publish the docker image with a more recent cf cli binary.

## Logs and Screenshots

N/A (but we can provide some if necessary)

**Comment by fredwangwang** [comment]
merged. Closing
