### ISSUE TITLE
Specifying HAProxy IPs ow in teh range causes IP conflicts in Ops Mgr

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/pcf-pipelines#39]
I'm unsure if this is specific to the pipeline, om, or Ops Mgr. But I set haproxy static ip, and got the message ```"errors":["IP '192.168.144.11' is already taken, cannot be taken for 'cf-f7fc90f1f948b5ffffb9_ha_proxy-f7a7297e6fc566c528ea-partition-21a67ea37bbec67c3833'"]}``` during apply.

```
deployment_network_name: "DEPLOYMENT"
deployment_vsphere_network: "VM Network"   # vCenter Deployment network name
deployment_nw_cidr: 192.168.128.0/17          # Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range: "192.168.128.1-192.168.144.9, 192.168.159.250-192.168.255.255"    # Deployment network exclusion range
deployment_nw_dns: 192.168.3.14           # Deployment network DNS
deployment_nw_gateway: 192.168.128.1       # Deployment network Gateway
deployment_nw_azs: PCF Cluster           # Comma seperated list of AZ's to be associated with this network

ha_proxy_ips: 192.168.144.111, 192.168.144.112          # Comma-separated list of static IPs
```

**Comment by ryanpei** [comment]
@haydonryan was the HAProxy field populated with 192.168.144.11 or 192.168.144.111 when this error occurred? It looks like your error message states a different address than what you requested in your params (.11 vs .111)

**Comment by haydonryan** [comment]
It was populated with .11, I had to change it to .111 to get it to work.

**Comment by ryanpei** [comment]
It's Ops Mgr wonkiness. cc @sadvani
