### ISSUE TITLE
upgrade ops man task failing on govc import.ova

### ISSUE THREAD

**Issue by bhudlemeyer** [pivotal-cf/pcf-pipelines#4]
govc import.ova is failing with below message

```
`Running` govc import.ova -options=opsman_settings.json -name=OpsManager-1.9.3-201702240222 -k=true -u=VCENTER -ds=DS -dc=DC -pool=POOL  -folder=FOLDER /tmp/build/39dbd1bf/pivnet-opsmgr/pcf-vsphere-1.9.3.ova
./govc/govc_linux_amd64: no file specified
```

I think that something is conflicting. As when I remove all but the below options deploy begins to work correctly.

```
Running govc import.ova -options=opsman_settings.json -name=OpsManager-1.9.3-201702240222 -k=true  -folder=FOLDER /tmp/build/39dbd1bf/pivnet-opsmgr/pcf-vsphere-1.9.3.ova

[24-02-17 02:56:48] Uploading pivotal-ops-manager-disk1.vmdk... (28%, 16.5MiB/s)
```

**Comment by bhudlemeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/2275490/23293205/2668f7e2-fa22-11e6-9cf4-9b23fb6b02c9.png)

After modifing 
**pcf-pipelines/tasks/deploy-opsman-vm/task.sh**

upgrade finishes successully. 

I have do not have pull request access but have added the mods to my forked repo bhudlemeyer/pcf-pipelines

on the update-deploy-opsman-vm branch.

**Comment by bhudlemeyer** [comment]
Created pull request [https://github.com/c0-ops/pcf-pipelines/pull/5] to resolve error.

**Comment by krishicks** [comment]
Hi @bhudlemeyer,

The upgrade-opsman-vsphere pipeline is currently being worked on, so we probably won't get around to pulling in your PR. It's switching to using a new method for creating the new VM, and won't be using `govc` at all.

I'll leave it open for now and close it when we have the update ready.

**Comment by bhudlemeyer** [comment]
Ok no worries. I will continue to use the forked update until code is updated with the new deploy method.

**Comment by krishicks** [comment]
I created a story to track this issue: https://www.pivotaltracker.com/story/show/145167975

We stopped working on replacing `govc` with `cliaas` to work on other pipelines.

**Comment by krishicks** [comment]
Closing this as per https://github.com/pivotal-cf/pcf-pipelines/pull/5.
