### ISSUE TITLE
Feature request - Upgrade ERT pipeline

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/pcf-pipelines#41]
Can we please make the upload-tile task "waiting for opsmgr" message not scroll forever while waiting for a response.  It takes ten minutes to time out, so it gets quite long.  Thanks
![screen shot 2017-05-03 at 9 54 26 am](https://cloud.githubusercontent.com/assets/3813241/25672027/f039199a-2fe6-11e7-9aea-b9c9b1b09885.png)

**Comment by krishicks** [comment]
This is something that lives in the `om-linux` tool; it's not controlled by us.

Feel free to open an issue there: https://github.com/pivotal-cf/om
