### ISSUE TITLE
Track updates metrics

### ISSUE THREAD

**Issue by phopper-pivotal** [pivotal-cf/pcf-pipelines#44]
looking at manual tasks once could track and quantify the time/effort it takes to upgrade services, application containers (tomcat for instance) and upgrade the OS. are there any capture details as part of these pipelines that could be used to quantify across tile, platform and stemcell upgrades? possibly output in each report as a stepping stone to storing externally to capture.

**Comment by krishicks** [comment]
@phopper-pivotal This information is available within Concourse when the build runs. I am hesitant to add anything about tracking to the pipelines given there's no one way to do metrics, nor would we have a good way for people to opt in (or out) of them easily.

Is there a reason you aren't able to use this information as it's presented in Concourse? Each job's runtime is available for each build.

**Comment by ryanpei** [comment]
closing this for now. please re-open another issue if you do not think Concourse itself addresses this appropriately.
