### ISSUE TITLE
install-pcf/aws readme is inaccurate

### ISSUE THREAD

**Issue by akumria** [pivotal-cf/pcf-pipelines#46]
With commit 3da8645ca92bb7f51d6c41e832b02de49ea65551 the upstream aws-concourse repository was deprecated. The majority of the tasks were brought in but the README references `pcfaws_terraform_pipeline.yml` which does not exist.

Either the README.md is wrong or the file was missed.

**Comment by krishicks** [comment]
@akumria Correct, this file should now be referred to as `install-pcf/aws/params.yml`, and the reference to `pcfaws_terraform_pipeline.yml` should be `install-pcf/aws/pipeline.yml`.

**Comment by abbyachau** [comment]
Hi @akumria, we've updated the install-pcf/aws README - thanks for opening this issue.
