### ISSUE TITLE
install-pcf pipeline for vsphere fails on tcp ports

### ISSUE THREAD

**Issue by forddonald** [pivotal-cf/pcf-pipelines#50]
When disabling tcp routing, left tcp ports blank. Job failed at config-elastic-runtime-tile stage config-er-tile with error:

staging cf 1.11.0-build.49
finished staging
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 09 May 2017 20:10:08 GMT
Etag: W/"072de635532b82c376c8c599b299e176"
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: ea690d92-d7f4-483a-ab86-e478f443ad82
X-Runtime: 0.193366
X-Xss-Protection: 1; mode=block
Using self signed certificates generated using Ops Manager...
configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 09 May 2017 20:10:10 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 39a7affc-fb61-4955-8c67-bbaec5abbb0a
X-Runtime: 0.493735
X-Xss-Protection: 1; mode=block

57
{"errors":{".properties.tcp_routing.enable.reservable_ports":["Value can't be blank"]}}
0

**Comment by forddonald** [comment]
Also, adding TCP ports to use and leaving the tcp routing feature off, yields this error:

cf 1.11.0-build.49 is already staged
Status: 200 OK
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 09 May 2017 20:19:23 GMT
Etag: W/"9123de8a4769ecb274dd7f5a9407b638"
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: e6d86455-7bdd-4717-9e98-46970515443c
X-Runtime: 0.106267
X-Xss-Protection: 1; mode=block
Using self signed certificates generated using Ops Manager...
configuring product...
setting properties
could not execute "configure-product": failed to configure product: request failed: unexpected response:
HTTP/1.1 422 Unprocessable Entity
Transfer-Encoding: chunked
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Tue, 09 May 2017 20:19:25 GMT
Server: nginx/1.4.6 (Ubuntu)
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 905a4c44-0a25-4261-a7f5-de790971aef8
X-Runtime: 0.540742
X-Xss-Protection: 1; mode=block

6c
{"errors":{".properties.tcp_routing":["You can only change properties that are under the selected option"]}}
0

**Comment by forddonald** [comment]
Probably same issue as 
https://github.com/pivotal-cf/pcf-pipelines/issues/28

**Comment by krishicks** [comment]
I agree that it's the same as #28 and we should close this issue, and also reference it from the other one because of the logs.
