### ISSUE TITLE
Opsman should be associated with an elastic ip address

### ISSUE THREAD

**Issue by krishicks** [pivotal-cf/pcf-pipelines#51]
From @bijukunjummen:

> The terraform scripts for provisioning an opsman vm should associate an elastic
> ip address with the opsman vm, otherwise the upgrade scripts for opsman tends
> to fail as it tries to associate the non-elastic ip to the new instance and
> fails.

Moved from https://github.com/pivotal-cf/aws-concourse/issues/14.

**Comment by krishicks** [comment]
@bijukunjummen We should think about the approach to this given https://github.com/pivotal-cf/cliaas/issues/2:

> Ops Manager has a private IP
> Customer has VPN/Direct connect to the VPC
> DNS is assigned to the private IP
> 
> When replace the VM the private IPs are not swapped

Currently we swap the external IP only, but this is an assumption that we made that probably should be configurable.

**Comment by svrc-pivotal** [comment]
the workaround i've had to do for this for now is to use a CNAME record from opsman.mydomain to ec2-xx-xx-xx-xx.compute-1.amazonaws.com to be able to access the OpsMan through the private network as AWS will do split horizon DNS resulation on the underlying ec2 DNS A record.

**Comment by abbyachau** [comment]
Hi @bijukunjummen thanks for raising this issue. We've applied a fix for this issue and have verified that the fix works as expected. If you have any feedback, please do not hesitate to reach out by creating a new issue. Thanks.
