### ISSUE TITLE
configure-ert job for AWS CF Install should be synced up with the one for vSphere

### ISSUE THREAD

**Issue by bijukunjummen** [pivotal-cf/pcf-pipelines#58]
The Configure-ert job for AWS CF install(`tasks/install-ert/configure-ert.sh`) is very different from a more generic one here (`tasks/config-ert/task.sh`). Ideally the latter one should be used. This will also as a side effect fix up #53 as there is a PR in works for the VSphere one.

**Comment by ryanpei** [comment]
closing this out in favor of https://www.pivotaltracker.com/story/show/145544707
