### ISSUE TITLE
Pipelines tasks refer to virtmerlin/c0-worker, c0 team dockerhub may be better?

### ISSUE THREAD

**Issue by akumria** [pivotal-cf/pcf-pipelines#66]
See ref: https://github.com/pivotal-cf/aws-concourse/issues/12 (that repository is now deprecated).

This is just a copy of the issue.

> @bijukunjummen 
> I noticed that some of the pipeline steps refer to this docker image virtmerlin/c0-worker, wouldn't hosting and using docker images from a team dockerhub a better idea.

> @krishicks 
> We have chores to replace any non-cflinuxfs2 images with either cflinuxfs2 or one based on
> cflinuxfs2 that we maintain.
>
>They're here:
>
>https://www.pivotaltracker.com/story/show/144251129
>https://www.pivotaltracker.com/story/show/144251109
>https://www.pivotaltracker.com/story/show/144251095

**Comment by krishicks** [comment]
We already have a story for this and have nearly completed the work.
