### ISSUE TITLE
why a fork of om

### ISSUE THREAD

**Issue by akumria** [pivotal-cf/pcf-pipelines#67]
See ref: https://github.com/pivotal-cf/aws-concourse/issues/8

This is just a copy of the issue.

> @wjjk940
> https://github.com/c0-ops/om (0.8.1) https://github.com/pivotal-cf/om/releases (0.22.0) — I don’t know why the script isn’t using om [options] configure-bosh [<args>]

> @ryanpei 
> this is a good point. we should refactor the pipelines to use om configure-bosh now that this is supported in om master.

**Comment by ryanpei** [comment]
yup, and it's prioritized in our backlog but we haven't gotten to it yet. thanks for everyone's patience on this!

i'll close this out as a duplicate issue, for now

**Comment by ryanpei** [comment]
actually, i should close the other one. my bad.

**Comment by zachgersh** [comment]
@ryanpei could you also please make sure to delete your fork when finished 😄

**Comment by ryanpei** [comment]
yup, will do!

**Comment by krishicks** [comment]
Removed the beta om usage in https://github.com/pivotal-cf/pcf-pipelines/commit/11923ad. The fork can be deleted whenever.
