### ISSUE TITLE
OPSMAN_URI parameter likely redundant

### ISSUE THREAD

**Issue by akumria** [pivotal-cf/pcf-pipelines#68]
See ref: https://github.com/pivotal-cf/aws-concourse/issues/13

This is just a copy of that issue.

> @bijukunjummen 
> The `OPSMAN_URI` parameter is likely to be redundant - in some of the pipeline steps it is derived as `https://opsman.$ERT_DOMAIN`, if by any chance a different `OPSMAN_URI` is provided the import-stemcell step fails as the url's don't match up. We should either use `OPSMAN_URI` at all places or remove `OPSMAN_URI` and derive the url.

> @ryanpei 
> @bijukunjummen so we would replace `OPSMAN_URI` with `ERT_DOMAIN` in all places where it is > currently used?

> @bijukunjummen 
> Yes, I think so @ryanpei, OR make use of the `OPSMAN_URI` everywhere a opsman's url is required instead of deriving it as `https://opsman.$ERT_DOMAIN`. Former may be a good start though.

**Comment by akumria** [comment]
Personally I think it would be simpler to consistently use `OPSMAN_URI` everywhere. Then the derivation can be done once -- and also allow for overrides.

It might also help for https://github.com/pivotal-cf/aws-concourse/issues/14 too

**Comment by krishicks** [comment]
I don't agree with the original issue. We use `OPSMAN_URI` directly all over the place. Perhaps in the scope of `aws-concourse` it wasn't, but no matter as `aws-concourse` is deprecated.
