### ISSUE TITLE
create infrastructure fails on GCP

### ISSUE THREAD

**Issue by mcb** [pivotal-cf/pcf-pipelines#78]
When running the `create-infrastructure` part of the pipeline, this fails with 

```
The module root could not be found. There is nothing to output.
```

Changing the terraform output command to 

```
output_json=$(/opt/terraform/terraform output -json -state=terraform-$version.tfstate)
```

like in https://github.com/pivotal-cf/pcf-pipelines/blob/ae469a2e305871f9735a70b4f73f437a937fb67d/tasks/install-pcf-gcp/create-infrastructure/task.sh#L51

it works.

**Comment by krishicks** [comment]
This no longer applies as I've reverted the addition of terraform.

**Comment by mcb** [comment]
@krishicks Well, this does not apply to your revert. This fixes another issue with terraform where terraform error'd out with `The module root could not be found. There is nothing to output.`

**Comment by krishicks** [comment]
Ah, my mistake.

**Comment by krishicks** [comment]
Thanks, merged!
