### ISSUE TITLE
Reconsider approach with cliaas

### ISSUE THREAD

**Issue by svrc-pivotal** [pivotal-cf/pcf-pipelines#84]
Please take this as a suggestion / constructive feedback after using these for a few months on AWS, Azure, and vSphere

The most easy to debug and customize IaaS for pcf-upgrades and installs is vSphere because of the use of **govc**.   Whereas the other clouds Ops Man pipelines have not once done what I'd expect, and have required many rounds of debugging to tweak my setup to the expectations of **cliaas**.

While golang as a CLI is great, using golang effectively as a scripting language (as it is here, since there are so many variations in the task) has major maintainability problems in the wild.   

These pipelines need to be customized for specific customer environments, and unless cliaas is going to handle almost every permutation of variation, it's a black box to system administrators who are never going to learn golang , so people will wind up writing their own scripted CLI , or IaaS Template (Azure ARM template, AWS CF, etc.) or terraform-based version of the task.  I'd much rather have something easily tinker-able like this.   

that said if the goal is to have cliaas "just handle it all", kudos, it's just not there for a while. 

Examples include
- use of private vs public IPs,  #51 
- customized disk settings (it uses the VMDK/VHD/AMI defaults which are usually far too low)
- reserved IOPS for disks
- multi-homed NICs for Ops Man
- common post-processing for Ops Man including: TLS certs, LDAP PAM setup

**Comment by krishicks** [comment]
Go isn't being used as a scripting language here, it's using the SDKs provided by the IaaS. `govc` does the same; it just happens to be a binary that's also released by VMWare.

`cliaas` is there to handle a specific problem of us wanting a single interface for doing specific things, like `replace-vm`. It is not meant to "handle it all".

If there are specific features you'd like or issues you are having with the pipelines, please open issues for them as they arise so we can address them.
