### ISSUE TITLE
Mismatch in pcf-pipeline-tarball filename in pipelines

### ISSUE THREAD

**Issue by nsagoo-pivotal** [pivotal-cf/pcf-pipelines#9]
I downloaded the Concourse Automation Pipeline from PivNet to update an instance of PCF. I came across a minor error where the downloaded pcf-pipeline-tarball from pivnet did not match the filename present in the run command of the tarball-unpack task within upgrad-tile job. Same issue with upgrade-buildpack pipeline where the tarball-unpack task in for each buildpack has a mismatch in the pcf-pipeline tarball and the product_version define in the resource section. 

- name: pcf-pipelines-tarball
  type: pivnet
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.1.0

  - task: tarball-unpack
    config:
      inputs: [ { name: pcf-pipelines-tarball } ]
      outputs: [ { name: pcf-pipelines } ]
      platform: linux
      image_resource: { type: docker-image, source: {repository: cloudfoundry/cflinuxfs2} }
      run: { path: tar, args: [ "-xvzf", "pcf-pipelines-tarball/pcf-pipelines.tgz" ] }

The last line should be: 
run:` { path: tar, args: [ "-xvzf", "pcf-pipelines-tarball/pcf-pipelines-v0.1.0.tgz" ] }

To make it resilient, it would be better if chainging the product_version of pcf-pipeline-tarball does not require changing the run task in the tarball-unpack task.

**Comment by krishicks** [comment]
Hi,

This has been fixed in 0.3.0.

Cheers,

KH
