### ISSUE TITLE
replace-opsman-vm task fails in GCP upgrade-opsmgr pipeline

### ISSUE THREAD

**Issue by cpage-pivotal** [pivotal-cf/pcf-pipelines#96]
Using 0.14.1 release of pcf-pipelines. Running on GCP, attempting to upgrade from Ops Manager 1.10.3 to 1.10.8

The replace-opsman-vm task executes the following command:
`cliaas-linux replace-vm --config cliaas-config/config.yml --identifier "ops-manager-1-10-3"`

After a couple of minutes, the Ops Manager VM shuts down:

![image](https://cloud.githubusercontent.com/assets/10927227/26592298/011f5c2a-4526-11e7-8799-9472d942f155.png)

However, the cliaas-linux remains unresponsive until the end of the 10-minute timeout period, and then errors out with:

`error: waitforstatus after stopvm failed: polling for status timed out`

**Comment by abbyachau** [comment]
Hey @cpage-pivotal, thanks for opening this issue and sorry for the late response. Are you still having issues with this upgrade? Have you tried using the latest [release](https://github.com/pivotal-cf/pcf-pipelines/releases) of pcf-pipelines?

**Comment by abbyachau** [comment]
Hi @cpage-pivotal, we are going to close this issue due to inactivity. Please do not hesitate to open a new issue if you have any further questions or issues.  Please also review our list of new releases (https://github.com/pivotal-cf/pcf-pipelines/releases). Thanks.
